
BEGIN;
LOCK TABLE works IN SHARE MODE;
INSERT INTO works VALUES (1,'Twelfth Night','Twelfth Night, Or What You Will',1599,'Comedy');
INSERT INTO works VALUES (2,'All''s Well That Ends Well','All''s Well That Ends Well',1602,'Comedy');
INSERT INTO works VALUES (3,'Antony and Cleopatra','Antony and Cleopatra',1606,'Tragedy');
INSERT INTO works VALUES (4,'As You Like It','As You Like It',1599,'Comedy');
INSERT INTO works VALUES (5,'Comedy of Errors','The Comedy of Errors',1589,'Comedy');
INSERT INTO works VALUES (6,'Coriolanus','Coriolanus',1607,'Tragedy');
INSERT INTO works VALUES (7,'Cymbeline','Cymbeline, King of Britain',1609,'History');
INSERT INTO works VALUES (8,'Hamlet','Tragedy of Hamlet, Prince of Denmark, The',1600,'Tragedy');
INSERT INTO works VALUES (9,'Henry IV, Part I','History of Henry IV, Part I',1597,'History');
INSERT INTO works VALUES (10,'Henry IV, Part II','History of Henry IV, Part II',1597,'History');
INSERT INTO works VALUES (11,'Henry V','History of Henry V',1598,'History');
INSERT INTO works VALUES (12,'Henry VI, Part I','History of Henry VI, Part I',1591,'History');
INSERT INTO works VALUES (13,'Henry VI, Part II','History of Henry VI, Part II',1590,'History');
INSERT INTO works VALUES (14,'Henry VI, Part III','History of Henry VI, Part III',1590,'History');
INSERT INTO works VALUES (15,'Henry VIII','History of Henry VIII',1612,'History');
INSERT INTO works VALUES (16,'Julius Caesar','The Tragedy of Julius Caesar',1599,'Tragedy');
INSERT INTO works VALUES (17,'King John','History of King John',1596,'History');
INSERT INTO works VALUES (18,'King Lear','The Tragedy of King Lear',1605,'Tragedy');
INSERT INTO works VALUES (19,'Lover''s Complaint','A Lover''s Complaint',1609,'Poem');
INSERT INTO works VALUES (20,'Love''s Labour''s Lost','Love''s Labour''s Lost',1594,'Comedy');
INSERT INTO works VALUES (21,'Macbeth','The Tragedy of Macbeth',1605,'Tragedy');
INSERT INTO works VALUES (22,'Measure for Measure','Measure for Measure',1604,'Comedy');
INSERT INTO works VALUES (23,'Merchant of Venice','Merchant of Venice, The',1596,'Comedy');
INSERT INTO works VALUES (24,'Merry Wives of Windsor','Merry Wives of Windsor, The',1600,'Comedy');
INSERT INTO works VALUES (25,'Midsummer Night''s Dream','A Midsummer Night''s Dream',1595,'Comedy');
INSERT INTO works VALUES (26,'Much Ado about Nothing','Much Ado about Nothing',1598,'Comedy');
INSERT INTO works VALUES (27,'Othello','The Tragedy of Othello, Moor of Venice',1604,'Tragedy');
INSERT INTO works VALUES (28,'Passionate Pilgrim','The Passionate Pilgrim',1598,'Poem');
INSERT INTO works VALUES (29,'Pericles','Pericles, Prince of Tyre',1608,'History');
INSERT INTO works VALUES (30,'Phoenix and the Turtle','The Phoenix and the Turtle',1601,'Poem');
INSERT INTO works VALUES (31,'Rape of Lucrece','The Rape of Lucrece',1594,'Poem');
INSERT INTO works VALUES (32,'Richard II','History of Richard II',1595,'History');
INSERT INTO works VALUES (33,'Richard III','History of Richard III',1592,'History');
INSERT INTO works VALUES (34,'Romeo and Juliet','The Tragedy of Romeo and Juliet',1594,'Tragedy');
INSERT INTO works VALUES (35,'Sonnets','Sonnets',1609,'Sonnet');
INSERT INTO works VALUES (36,'Taming of the Shrew','The Taming of the Shrew',1593,'Comedy');
INSERT INTO works VALUES (37,'Tempest','The Tempest',1611,'Comedy');
INSERT INTO works VALUES (38,'Timon of Athens','The Tragedy of Timon of Athens',1607,'Tragedy');
INSERT INTO works VALUES (39,'Titus Andronicus','Titus Andronicus',1593,'Tragedy');
INSERT INTO works VALUES (40,'Troilus and Cressida','Troilus and Cressida',1601,'Tragedy');
INSERT INTO works VALUES (41,'Two Gentlemen of Verona','Two Gentlemen of Verona',1594,'Comedy');
INSERT INTO works VALUES (42,'Venus and Adonis','Venus and Adonis',1593,'Poem');
INSERT INTO works VALUES (43,'The Winter''s Tale','The Winter''s Tale',1610,'Comedy');
COMMIT;
