
BEGIN;
LOCK TABLE characters IN SHARE MODE;
INSERT INTO characters VALUES (1,'First Apparition','First Apparition','');
INSERT INTO characters VALUES (2,'First Citizen','First Citizen','');
INSERT INTO characters VALUES (3,'First Conspirator','First Conspirator','');
INSERT INTO characters VALUES (4,'First Gentleman','First Gentleman','');
INSERT INTO characters VALUES (5,'First Goth','First Goth','');
INSERT INTO characters VALUES (6,'First Murderer','First Murderer','');
INSERT INTO characters VALUES (7,'First Musician','First Musician','');
INSERT INTO characters VALUES (8,'First Musician','First Musician','');
INSERT INTO characters VALUES (9,'First Officer','First Officer','');
INSERT INTO characters VALUES (10,'First Player','1Play','');
INSERT INTO characters VALUES (11,'First Senator','First Senator','');
INSERT INTO characters VALUES (12,'First Senator','First Senator','A senator of Venice');
INSERT INTO characters VALUES (13,'First Servant','First Servant','');
INSERT INTO characters VALUES (14,'First Serving-Man','First Serving-Man','');
INSERT INTO characters VALUES (15,'First Soldier','First Soldier','');
INSERT INTO characters VALUES (16,'First Watchman','First Watchman','');
INSERT INTO characters VALUES (17,'First Watchman','First Watchman','');
INSERT INTO characters VALUES (18,'First Witch','First Witch','');
INSERT INTO characters VALUES (19,'Second Apparition','Second Apparition','');
INSERT INTO characters VALUES (20,'Second Conspirator','Second Conspirator','');
INSERT INTO characters VALUES (21,'Second Gentleman','Second Gentleman','');
INSERT INTO characters VALUES (22,'Second Goth','Second Goth','');
INSERT INTO characters VALUES (23,'Second Murderer','Second Murderer','');
INSERT INTO characters VALUES (24,'Second Musician','Second Musician','');
INSERT INTO characters VALUES (25,'Second Patrician','Second Patrician','');
INSERT INTO characters VALUES (26,'Second Senator','Second Senator','');
INSERT INTO characters VALUES (27,'Second Senator','Second Senator','A senator of Venice');
INSERT INTO characters VALUES (28,'Second Servant','Second Servant','');
INSERT INTO characters VALUES (29,'Second Serving-Man','Second Serving-Man','');
INSERT INTO characters VALUES (30,'Second Soldier','Second Soldier','');
INSERT INTO characters VALUES (31,'Second Watchman','Second Watchman','');
INSERT INTO characters VALUES (32,'Second Watchman','Second Watchman','');
INSERT INTO characters VALUES (33,'Second Witch','Second Witch','');
INSERT INTO characters VALUES (34,'Third Apparition','Third Apparition','');
INSERT INTO characters VALUES (35,'Third Conspirator','Third Conspirator','');
INSERT INTO characters VALUES (36,'Third Gentleman','Third Gentleman','');
INSERT INTO characters VALUES (37,'Third Goth','Third Goth','');
INSERT INTO characters VALUES (38,'Third Murderer','Third Murderer','');
INSERT INTO characters VALUES (39,'Third Musician','Third Musician','');
INSERT INTO characters VALUES (40,'Third Serving-Man','Third Serving-Man','');
INSERT INTO characters VALUES (41,'Third Watchman','Third Watchman','');
INSERT INTO characters VALUES (42,'Third Witch','Third Witch','');
INSERT INTO characters VALUES (43,'Fourth Gentleman','Fourth Gentleman','');
INSERT INTO characters VALUES (44,'Aaron','AARON','a Moor, beloved by Tamora');
INSERT INTO characters VALUES (45,'Abbot','Abbot','');
INSERT INTO characters VALUES (46,'Lord Abergavenny','ABERGAVENNY','');
INSERT INTO characters VALUES (47,'Abhorson','ABHORSON','an executioner');
INSERT INTO characters VALUES (48,'Abraham','ABRAHAM','Servant to Montague');
INSERT INTO characters VALUES (49,'Achilles','ACHILLES','a Greek prince');
INSERT INTO characters VALUES (50,'Adam','ADAM','servant to Oliver');
INSERT INTO characters VALUES (51,'Adriana','ADRIANA','wife to Antipholus of Ephesus');
INSERT INTO characters VALUES (52,'Adrian','ADRIAN','a lord');
INSERT INTO characters VALUES (53,'Aedile','Aedile','');
INSERT INTO characters VALUES (54,'Aegeon','AEGEON','a merchant of Syracuse');
INSERT INTO characters VALUES (55,'Aemilia','AEMILIA','wife to Aegeon, an abbess at Ephesus');
INSERT INTO characters VALUES (56,'Aemilius','AEMILIUS','a noble Roman');
INSERT INTO characters VALUES (57,'Aeneas','AENEAS','one of the Trojan commanders');
INSERT INTO characters VALUES (58,'Agamemnon','AGAMEMNON','the Greek general');
INSERT INTO characters VALUES (59,'Agrippa','AGRIPPA','friend to Caesar');
INSERT INTO characters VALUES (60,'Sir Andrew Aguecheek','SIR ANDREW','');
INSERT INTO characters VALUES (61,'Ajax','AJAX','a Greek prince');
INSERT INTO characters VALUES (62,'Alarbus','ALARBUS','son to Tamora');
INSERT INTO characters VALUES (63,'Alcibiades','ALCIBIADES','an Athenian captain');
INSERT INTO characters VALUES (64,'Alexander','ALEXANDER','servant to Cressida');
INSERT INTO characters VALUES (65,'Alexander Iden','IDEN','a Kentish gentleman');
INSERT INTO characters VALUES (66,'Alexas','ALEXAS','attendant on Cleopatra');
INSERT INTO characters VALUES (67,'Alice','ALICE','a lady attending on Princess Katherine');
INSERT INTO characters VALUES (68,'All','All','');
INSERT INTO characters VALUES (69,'All','All','');
INSERT INTO characters VALUES (70,'All Citizens','All Citizens','');
INSERT INTO characters VALUES (71,'All Conspirators','All Conspirators','');
INSERT INTO characters VALUES (72,'All','All','');
INSERT INTO characters VALUES (73,'All','All','');
INSERT INTO characters VALUES (74,'All the Goths','All the Goths','');
INSERT INTO characters VALUES (75,'All','All','');
INSERT INTO characters VALUES (76,'All','All','');
INSERT INTO characters VALUES (77,'All','All','');
INSERT INTO characters VALUES (78,'All','All','');
INSERT INTO characters VALUES (79,'All','All','');
INSERT INTO characters VALUES (80,'All','All','');
INSERT INTO characters VALUES (81,'All','All','');
INSERT INTO characters VALUES (82,'All','All','');
INSERT INTO characters VALUES (83,'All Ladies','All Ladies','');
INSERT INTO characters VALUES (84,'All Lords','All Lords','');
INSERT INTO characters VALUES (85,'All Lords','All Lords','');
INSERT INTO characters VALUES (86,'All','ALL','');
INSERT INTO characters VALUES (87,'All','All','');
INSERT INTO characters VALUES (88,'All','All','');
INSERT INTO characters VALUES (89,'All','All','');
INSERT INTO characters VALUES (90,'All','All','');
INSERT INTO characters VALUES (91,'All The People','All The People','');
INSERT INTO characters VALUES (92,'All','All','');
INSERT INTO characters VALUES (93,'All','All','');
INSERT INTO characters VALUES (94,'All Servants','All Servants','');
INSERT INTO characters VALUES (95,'All','All','');
INSERT INTO characters VALUES (96,'All','All','');
INSERT INTO characters VALUES (97,'All','All','');
INSERT INTO characters VALUES (98,'All','ALL','');
INSERT INTO characters VALUES (99,'Alonso','ALONSO','king of Naples');
INSERT INTO characters VALUES (100,'Ambassador','Ambassador','');
INSERT INTO characters VALUES (101,'Amiens','AMIENS','lord attending on the banished Duke');
INSERT INTO characters VALUES (102,'Andromache','ANDROMACHE','wife to Hector');
INSERT INTO characters VALUES (103,'Angelo','ANGELO','a goldsmith');
INSERT INTO characters VALUES (104,'Angelo','ANGELO','deputy');
INSERT INTO characters VALUES (105,'Angus','ANGUS','Nobleman of Scotland');
INSERT INTO characters VALUES (106,'Anne Bullen','QUEEN ANNE','Katharine''s maid of honor, afterwards Queen');
INSERT INTO characters VALUES (107,'Anne Page','ANNE PAGE','Mistress Page''s daughter');
INSERT INTO characters VALUES (108,'Another','ANOTHER','Another');
INSERT INTO characters VALUES (109,'Antenor','ANTENOR','one of the Trojan commanders');
INSERT INTO characters VALUES (110,'Antigonus','ANTIGONUS','a lord of Sicilia');
INSERT INTO characters VALUES (111,'Antiochus','ANTIOCHUS','king of Antioch');
INSERT INTO characters VALUES (112,'Daughter of Antiochus','Daughter','');
INSERT INTO characters VALUES (113,'Antipholus of Ephesus','ANTIPHOLUS OF EPHESUS','twin brother of Antipholus of Syracuse, son to Aegeon and Aemilia');
INSERT INTO characters VALUES (114,'Antipholus of Syracuse','ANTIPHOLUS OF SYRACUSE','twin brother of Antipholus of Ephesus, son to Aegeon and Aemelia');
INSERT INTO characters VALUES (115,'Antonio','ANTONIO','Leonato''s brother');
INSERT INTO characters VALUES (116,'Antonio','ANTONIO','a sea captain, friend to Sebastain');
INSERT INTO characters VALUES (117,'Antonio','ANTONIO','a merchant of Venice');
INSERT INTO characters VALUES (118,'Antonio','ANTONIO','the King''s brother, the usurping Duke of Milan');
INSERT INTO characters VALUES (119,'Antonio','ANTONIO','father to Proteus');
INSERT INTO characters VALUES (120,'Antony','ANTONY','(Marcus Antonius)');
INSERT INTO characters VALUES (121,'Apemantus','APEMANTUS','a churlish philosopher');
INSERT INTO characters VALUES (122,'Apothecary','Apothecary','');
INSERT INTO characters VALUES (123,'Archidamus','ARCHIDAMUS','a lord of Bohemia');
INSERT INTO characters VALUES (124,'Ariel','ARIEL','an airy spirit');
INSERT INTO characters VALUES (125,'Artemidorus','ARTEMIDORUS','of Cnidos, a teacher of rhetoric.');
INSERT INTO characters VALUES (126,'Arthur','ARTHUR','Duke of Bretagne, nephew to the king');
INSERT INTO characters VALUES (127,'Arviragus','ARVIRAGUS','son to Cymbeline, disguised under the name of Cadwal, supposed son to Morgan');
INSERT INTO characters VALUES (128,'Attendants','Attendants','');
INSERT INTO characters VALUES (129,'Attendant','Attendant','');
INSERT INTO characters VALUES (130,'Attendant','Attendant','');
INSERT INTO characters VALUES (131,'Attendant','ATTENDANT','');
INSERT INTO characters VALUES (132,'Audrey','AUDREY','a country wench');
INSERT INTO characters VALUES (133,'Duke of Aumerle','DUKE OF AUMERLE','son of the Duke of York');
INSERT INTO characters VALUES (134,'Autolycus','AUTOLYCUS','a rogue');
INSERT INTO characters VALUES (135,'Bagot','BAGOT','servant to King Richard II');
INSERT INTO characters VALUES (136,'Balthasar','BALTHASAR','Servant to Romeo');
INSERT INTO characters VALUES (137,'Balthasar','BALTHASAR','Attendant on Don Pedro');
INSERT INTO characters VALUES (138,'Balthasar','BALTHASAR','servant to Portia');
INSERT INTO characters VALUES (139,'Balthazar','BALTHAZAR','a merchant');
INSERT INTO characters VALUES (140,'Banditti','Banditti','');
INSERT INTO characters VALUES (141,'Banquo','BANQUO','General of the King''s army');
INSERT INTO characters VALUES (142,'Baptista Minola','BAPTISTA','a gentleman of Padua');
INSERT INTO characters VALUES (143,'Lord Bardolph','LORD BARDOLPH','');
INSERT INTO characters VALUES (144,'Bardolph','BARDOLPH','');
INSERT INTO characters VALUES (145,'Bardolph','BARDOLPH','sharper attending on Falstaff');
INSERT INTO characters VALUES (146,'Barnardine','BARNARDINE','a dissolute prisoner');
INSERT INTO characters VALUES (147,'Bassanio','BASSANIO','Antonio''s friend, suitor likewise to Portia');
INSERT INTO characters VALUES (148,'Basset','BASSET','of the Red Rose, or Lancaster, faction');
INSERT INTO characters VALUES (149,'Bassianus','BASSIANUS','brother to Saturninus; in love with Lavinia');
INSERT INTO characters VALUES (150,'Bastard of Orleans','BASTARD OF ORLEANS','');
INSERT INTO characters VALUES (151,'Bates','BATES','soldier in King Henry''s army');
INSERT INTO characters VALUES (152,'Bawd','Bawd','');
INSERT INTO characters VALUES (153,'Beadle','Beadle','');
INSERT INTO characters VALUES (154,'First Beadle','FIRST BEADLE','');
INSERT INTO characters VALUES (155,'Second Beadle','SECOND BEADLE','');
INSERT INTO characters VALUES (156,'Beatrice','BEATRICE','Niece to Leonato');
INSERT INTO characters VALUES (157,'Duke of Bedford','BEDFORD','brother to Henry IV, uncle to Henry V');
INSERT INTO characters VALUES (158,'Belarius','BELARIUS','a banished lord, disguised under the name of Morgan');
INSERT INTO characters VALUES (159,'Sir Toby Belch','SIR TOBY BELCH','uncle to Olivia');
INSERT INTO characters VALUES (160,'Benedick','BENEDICK','A young lord of Padua');
INSERT INTO characters VALUES (161,'Benvolio','BENVOLIO','Nephew to Montague, and friend to Romeo');
INSERT INTO characters VALUES (162,'Berkeley','BERKELEY','a gentleman attending on Lady Anne');
INSERT INTO characters VALUES (163,'Bernardo','Ber','sentinel');
INSERT INTO characters VALUES (164,'Bertram','BERTRAM','Count of Rousillon');
INSERT INTO characters VALUES (165,'George Bevis','BEVIS','a follower of Cade');
INSERT INTO characters VALUES (166,'Bianca','BIANCA','');
INSERT INTO characters VALUES (167,'Bianca','BIANCA','Mistress to Cassio');
INSERT INTO characters VALUES (168,'Lord Bigot','BIGOT','');
INSERT INTO characters VALUES (169,'Biondello','BIONDELLO','');
INSERT INTO characters VALUES (170,'Biron','BIRON','lord attending on the king');
INSERT INTO characters VALUES (171,'Bishop of Carlisle','BISHOP OF CARLISLE','');
INSERT INTO characters VALUES (172,'Bishop Lincoln','LINCOLN','');
INSERT INTO characters VALUES (173,'Blanch','BLANCH','of Spain, niece to King John');
INSERT INTO characters VALUES (174,'Blunt','BLUNT','');
INSERT INTO characters VALUES (175,'Blunt','Blunt','');
INSERT INTO characters VALUES (176,'Boatswain','Boatswain','');
INSERT INTO characters VALUES (177,'Bolingbroke','BOLINGBROKE','a conjurer');
INSERT INTO characters VALUES (178,'Bona','BONA','sister to the French Queen');
INSERT INTO characters VALUES (179,'Borachio','BORACHIO','Follower of Don Juan');
INSERT INTO characters VALUES (180,'Both','Both','');
INSERT INTO characters VALUES (181,'Both Citizens','Both Citizens','');
INSERT INTO characters VALUES (182,'Both','Both','');
INSERT INTO characters VALUES (183,'Both','Both','');
INSERT INTO characters VALUES (184,'Both','Both','');
INSERT INTO characters VALUES (185,'Both','Both','');
INSERT INTO characters VALUES (186,'Both','Both','');
INSERT INTO characters VALUES (187,'Both','Both','');
INSERT INTO characters VALUES (188,'Both Tribunes','Both Tribunes','');
INSERT INTO characters VALUES (189,'Bottom','BOTTOM','a weaver');
INSERT INTO characters VALUES (190,'Boult','BOULT','Pandar''s servant');
INSERT INTO characters VALUES (191,'Duke of Bourbon','BOURBON','');
INSERT INTO characters VALUES (192,'Boyet','BOYET','lord attending on the princess of France');
INSERT INTO characters VALUES (193,'Boy','Boy','');
INSERT INTO characters VALUES (194,'Boy','Boy','son of the Master-Gunner');
INSERT INTO characters VALUES (195,'Boy','Boy','');
INSERT INTO characters VALUES (196,'Boy','Boy','a young son of Clarence');
INSERT INTO characters VALUES (197,'Boy','Boy','servant to Troilus');
INSERT INTO characters VALUES (198,'Brabantio','BRABANTIO','A senator of Venice');
INSERT INTO characters VALUES (199,'Brandon','BRANDON','');
INSERT INTO characters VALUES (200,'Brothers','BROTHERS','');
INSERT INTO characters VALUES (201,'Brutus','BRUTUS','(Marcus Brutus)');
INSERT INTO characters VALUES (202,'Peter Bullcalf','BULLCALF','country soldier');
INSERT INTO characters VALUES (203,'Bushy','BUSHY','servant to King Richard II');
INSERT INTO characters VALUES (204,'Caithness','CAITHNESS','Nobleman of Scotland');
INSERT INTO characters VALUES (205,'Caius','CAIUS','kinsman to Titus');
INSERT INTO characters VALUES (206,'Caius Lucius','CAIUS LUCIUS','general of the Roman forces');
INSERT INTO characters VALUES (207,'Calchas','CALCHAS','a Trojan priest, taking part with the Greeks');
INSERT INTO characters VALUES (208,'Caliban','CALIBAN','a savage and deformed slave');
INSERT INTO characters VALUES (209,'Calpurnia','CALPURNIA','wife to Caesar');
INSERT INTO characters VALUES (210,'Earl of Cambridge','CAMBRIDGE','');
INSERT INTO characters VALUES (211,'Camillo','CAMILLO','a lord of Sicilia');
INSERT INTO characters VALUES (212,'Cardinal Campeius','CARDINAL CAMPEIUS','');
INSERT INTO characters VALUES (213,'Canidius','CANIDIUS','lieutenant-general to Antony');
INSERT INTO characters VALUES (214,'Archbishop of Canterbury','CANTERBURY','');
INSERT INTO characters VALUES (215,'Caphis','CAPHIS','servant to Timon''s creditors');
INSERT INTO characters VALUES (216,'Captain','Captain','');
INSERT INTO characters VALUES (217,'Captain','Captain','');
INSERT INTO characters VALUES (218,'Captain','Captain','');
INSERT INTO characters VALUES (219,'Captain','Capt','');
INSERT INTO characters VALUES (220,'Captain','Captain','');
INSERT INTO characters VALUES (221,'Captain','Captain','');
INSERT INTO characters VALUES (222,'Capucius','CAPUCIUS','Ambassador from the Emperor Charles V');
INSERT INTO characters VALUES (223,'Capulet','CAPULET','Head of the house of Capulet');
INSERT INTO characters VALUES (224,'Second Capulet','Second Capulet','An old man, cousin to Capulet');
INSERT INTO characters VALUES (225,'Cardinal Bourchier','CARDINAL','archbishop of Canterbury');
INSERT INTO characters VALUES (226,'Cardinal Pandulph','CARDINAL PANDULPH','the Pope''s legate');
INSERT INTO characters VALUES (227,'Carrier','Carrier','');
INSERT INTO characters VALUES (228,'Casca','CASCA','a conspirator against Caesar');
INSERT INTO characters VALUES (229,'Cassandra','CASSANDRA','daughter to Priam, a prophetess');
INSERT INTO characters VALUES (230,'Cassio','CASSIO','Othello''s lieutenant');
INSERT INTO characters VALUES (231,'Cassius','CASSIUS','a conspirator against Caesar');
INSERT INTO characters VALUES (232,'Young Cato','CATO','friend to Brutus');
INSERT INTO characters VALUES (233,'Celia','CELIA','daughter to Frederick');
INSERT INTO characters VALUES (234,'Ceres','CERES','presented by spirits');
INSERT INTO characters VALUES (235,'Cerimon','CERIMON','a lord of Ephesus');
INSERT INTO characters VALUES (236,'Chamberlain','Chamberlain','');
INSERT INTO characters VALUES (237,'Charles','CHARLES','wrestler to Frederick');
INSERT INTO characters VALUES (238,'Charles, King of France','CHARLES','king of France');
INSERT INTO characters VALUES (239,'Charmian','CHARMIAN','attendant on Cleopatra');
INSERT INTO characters VALUES (240,'Chatillon','CHATILLON','ambassador from France to King John');
INSERT INTO characters VALUES (241,'Lord Chief Justice','CHIEF JUSTICE','');
INSERT INTO characters VALUES (242,'Children','Children','');
INSERT INTO characters VALUES (243,'Chiron','CHIRON','son to Tamora');
INSERT INTO characters VALUES (244,'Chorus','Chorus','');
INSERT INTO characters VALUES (245,'Chorus','Chorus','');
INSERT INTO characters VALUES (246,'Chorus','Chorus','');
INSERT INTO characters VALUES (247,'Chorus','Chorus','');
INSERT INTO characters VALUES (248,'Christopher Urswick','CHRISTOPHER','a priest');
INSERT INTO characters VALUES (249,'Cicero','Ciceronis','Senator');
INSERT INTO characters VALUES (250,'Cinna','CINNA','a conspirator against Caesar');
INSERT INTO characters VALUES (251,'Cinna the Poet','CINNA THE POET','');
INSERT INTO characters VALUES (252,'Citizen','Citizen','');
INSERT INTO characters VALUES (253,'Citizens','Citizens','');
INSERT INTO characters VALUES (254,'Citizens','Citizens','');
INSERT INTO characters VALUES (255,'Citizens','Citizens','');
INSERT INTO characters VALUES (256,'Claudio','CLAUDIO','A young lord of Florence');
INSERT INTO characters VALUES (257,'Claudio','CLAUDIO','a young gentleman');
INSERT INTO characters VALUES (258,'Claudius','King','King of Denmark');
INSERT INTO characters VALUES (259,'Claudius','CLAUDIUS','servant to Brutus');
INSERT INTO characters VALUES (260,'Cleomenes','CLEOMENES','a lord of Sicilia');
INSERT INTO characters VALUES (261,'Cleon','CLEON','governor of Tarsus');
INSERT INTO characters VALUES (262,'Cleopatra','CLEOPATRA','queen of Egypt');
INSERT INTO characters VALUES (263,'Clerk of Chatham','Clerk','');
INSERT INTO characters VALUES (264,'Clerk','Clerk','');
INSERT INTO characters VALUES (265,'Clitus','CLITUS','servant to Brutus');
INSERT INTO characters VALUES (266,'Cloten','CLOTEN','son to the Queen by a former husband');
INSERT INTO characters VALUES (267,'First Clown','Clown','');
INSERT INTO characters VALUES (268,'Second Clown','Other','');
INSERT INTO characters VALUES (269,'Clown','Clown','');
INSERT INTO characters VALUES (270,'Clown','Clown','servant to the Countess');
INSERT INTO characters VALUES (271,'Clown','Clown','Servant to Othello');
INSERT INTO characters VALUES (272,'Clown','Clown','');
INSERT INTO characters VALUES (273,'Clown','Clown','son of the old Shepherd');
INSERT INTO characters VALUES (274,'Cobweb','COBWEB','a fairy');
INSERT INTO characters VALUES (275,'Sir John Colville','COLVILLE','');
INSERT INTO characters VALUES (276,'Cominius','COMINIUS','general against the Volscians');
INSERT INTO characters VALUES (277,'Commons','Commons','');
INSERT INTO characters VALUES (278,'Conrade','CONRADE','Follower of Don Juan');
INSERT INTO characters VALUES (279,'Constable of France','Constable','');
INSERT INTO characters VALUES (280,'Constance','CONSTANCE','mother to Arthur');
INSERT INTO characters VALUES (281,'Cordelia','Cor','daughter to Lear');
INSERT INTO characters VALUES (282,'Corin','CORIN','shepherd');
INSERT INTO characters VALUES (283,'Coriolanus','CORIOLANUS','previously Caius Marcius Coriolanus');
INSERT INTO characters VALUES (284,'Cornelius','Cor','courtier');
INSERT INTO characters VALUES (285,'Cornelius','CORNELIUS','a physician');
INSERT INTO characters VALUES (286,'Costard','COSTARD','a clown');
INSERT INTO characters VALUES (287,'Countess of Auvergne','COUNTESS OF AUVERGNE','');
INSERT INTO characters VALUES (288,'Countess','COUNTESS','mother to Bertram');
INSERT INTO characters VALUES (289,'Court','COURT','soldier in King Henry''s army');
INSERT INTO characters VALUES (290,'Courtezan','Courtezan','');
INSERT INTO characters VALUES (291,'Archbishop Cranmer','CRANMER','Archbishop of Canterbury');
INSERT INTO characters VALUES (292,'Cressida','CRESSIDA','daughter to Calchas');
INSERT INTO characters VALUES (293,'Crier','Crier','');
INSERT INTO characters VALUES (294,'Cromwell','CROMWELL','servant to Wolsey');
INSERT INTO characters VALUES (295,'Cupid','Cupid','');
INSERT INTO characters VALUES (296,'Curan','Cur','a courtier');
INSERT INTO characters VALUES (297,'Curio','CURIO','gentleman attending on the Duke');
INSERT INTO characters VALUES (298,'Curtis','CURTIS','');
INSERT INTO characters VALUES (299,'Cymbeline','CYMBELINE','king of Britain');
INSERT INTO characters VALUES (300,'Dardanius','DARDANIUS','servant to Brutus');
INSERT INTO characters VALUES (301,'Lewis the Dauphin','DAUPHIN','');
INSERT INTO characters VALUES (302,'Davy','DAVY','servant to Shallow');
INSERT INTO characters VALUES (303,'Decius Brutus','DECIUS BRUTUS','a conspirator against Caesar');
INSERT INTO characters VALUES (304,'Deiphobus','DEIPHOBUS','son of Priam, king of Troy');
INSERT INTO characters VALUES (305,'Demetrius','Demetrius','son to Tamora');
INSERT INTO characters VALUES (306,'Demetrius','DEMETRIUS','friend to Antony');
INSERT INTO characters VALUES (307,'Demetrius','DEMETRIUS','in love with Hermia');
INSERT INTO characters VALUES (308,'Dennis','DENNIS','shepherd');
INSERT INTO characters VALUES (309,'Sir Anthony Denny','DENNY','');
INSERT INTO characters VALUES (310,'Dercetas','DERCETAS','friend to Antony');
INSERT INTO characters VALUES (311,'Desdemona','DESDEMONA','Daughter to Brabantio and wife to Othello');
INSERT INTO characters VALUES (312,'Diana','DIANA','daughter to the Widow');
INSERT INTO characters VALUES (313,'Diana','DIANA','');
INSERT INTO characters VALUES (314,'Dick the Butcher','DICK','a follower of Cade');
INSERT INTO characters VALUES (315,'Diomedes','DIOMEDES','attendant on Cleopatra');
INSERT INTO characters VALUES (316,'Diomedes','DIOMEDES','a Greek prince');
INSERT INTO characters VALUES (317,'Dion','DION','a lord of Sicilia');
INSERT INTO characters VALUES (318,'Dionyza','DIONYZA','wife to Cleon');
INSERT INTO characters VALUES (319,'Doctor Butts','DOCTOR BUTTS','physician to the King');
INSERT INTO characters VALUES (320,'Doctor Caius','DOCTOR CAIUS','a French physician');
INSERT INTO characters VALUES (321,'Doctor','Doct','');
INSERT INTO characters VALUES (322,'Doctor','Doctor','');
INSERT INTO characters VALUES (323,'Dogberry','DOGBERRY','A constable');
INSERT INTO characters VALUES (324,'Dolabella','DOLABELLA','friend to Caesar');
INSERT INTO characters VALUES (325,'Domitius Enobarus','DOMITIUS ENOBARBUS','friend to Antony');
INSERT INTO characters VALUES (326,'Don Adriano de Armado','DON ADRIANO DE ARMADO','a fantastical Spaniard');
INSERT INTO characters VALUES (327,'Donalbain','DONALBAIN','Son of Duncan');
INSERT INTO characters VALUES (328,'Don John','DON JOHN','The prince''s bastard brother');
INSERT INTO characters VALUES (329,'Don Pedro','DON PEDRO','Prince of Arragon');
INSERT INTO characters VALUES (330,'Dorcas','DORCAS','a shepherdess');
INSERT INTO characters VALUES (331,'Second Drawer','SECOND DRAWER','');
INSERT INTO characters VALUES (332,'Third Drawer','THIRD DRAWER','');
INSERT INTO characters VALUES (333,'Dromio of Ephesus','DROMIO OF EPHESUS','twin brother to Dromio of Syracuse, and attendant on the two Antipholuses');
INSERT INTO characters VALUES (334,'Dromio of Syracuse','DROMIO OF SYRACUSE','twin brother to Dromio of Ephesus, and attendant on the two Antipholuses');
INSERT INTO characters VALUES (335,'Duchess of Gloucester','DUCHESS','');
INSERT INTO characters VALUES (336,'Duchess of York','DUCHESS OF YORK','');
INSERT INTO characters VALUES (337,'Duchess of York','DUCHESS of YORK','mother to King Edward IV');
INSERT INTO characters VALUES (338,'Duke','DUKE','of Venice');
INSERT INTO characters VALUES (339,'Duke of Albany','Alb','');
INSERT INTO characters VALUES (340,'Duke of Alencon','ALENCON','');
INSERT INTO characters VALUES (341,'Duke','DUKE SENIOR','living in exile');
INSERT INTO characters VALUES (342,'Duke of Buckingham','BUCKINGHAM','');
INSERT INTO characters VALUES (343,'Duke of Buckingham','BUCKINGHAM','');
INSERT INTO characters VALUES (344,'Duke of Burgundy','Bur','');
INSERT INTO characters VALUES (345,'Duke of Burgundy','BURGUNDY','');
INSERT INTO characters VALUES (346,'Duke of Cornwall','Corn','');
INSERT INTO characters VALUES (347,'Duke of Florence','DUKE','');
INSERT INTO characters VALUES (348,'Duke of Milan','DUKE','father to Silvia');
INSERT INTO characters VALUES (349,'Duke of Norfolk','NORFOLK','');
INSERT INTO characters VALUES (350,'Duke of Norfolk','NORFOLK','');
INSERT INTO characters VALUES (351,'Duke of Suffolk','SUFFOLK','');
INSERT INTO characters VALUES (352,'Duke of Surrey','DUKE OF SURREY','');
INSERT INTO characters VALUES (353,'Duke of Venice','DUKE OF VENICE','');
INSERT INTO characters VALUES (354,'Dull','DULL','a constable');
INSERT INTO characters VALUES (355,'Dumain','DUMAIN','lord attending on the king');
INSERT INTO characters VALUES (356,'Duncan','DUNCAN','King of Scotland');
INSERT INTO characters VALUES (357,'Earl of Douglas','Earl of Douglas','');
INSERT INTO characters VALUES (358,'Earl of Kent','Kent','');
INSERT INTO characters VALUES (359,'Earl of Northumberland','NORTHUMBERLAND','');
INSERT INTO characters VALUES (360,'Earl of Northumberland','NORTHUMBERLAND','');
INSERT INTO characters VALUES (361,'Earl Oxford','OXFORD','');
INSERT INTO characters VALUES (362,'Henry, Earl of Richmond','HENRY OF RICHMOND','a youth');
INSERT INTO characters VALUES (363,'Earl of Suffolk','SUFFOLK','');
INSERT INTO characters VALUES (364,'Earl of Surrey','SURREY','');
INSERT INTO characters VALUES (365,'Earl of Surrey','SURREY','son of the Duke of Norfolk');
INSERT INTO characters VALUES (366,'Earl of Westmoreland','WESTMORELAND','');
INSERT INTO characters VALUES (367,'Edgar','Edg','son of Glouchester');
INSERT INTO characters VALUES (368,'Edmond, Earl of Rutland','RUTLAND','');
INSERT INTO characters VALUES (369,'Edmund','Edm','bastard son to Glouchester');
INSERT INTO characters VALUES (370,'Edmund of Langley','DUKE OF YORK','duke of York, uncle to the king');
INSERT INTO characters VALUES (371,'Edmund Mortimer','MORTIMER','Earl of March');
INSERT INTO characters VALUES (372,'King Edward IV (Plantagenet)', 'EDWARD', '');
INSERT INTO characters VALUES (373,'Egeus','EGEUS','father to Hermia');
INSERT INTO characters VALUES (374,'Eglamour','EGLAMOUR','agent for Silvia in her escape');
INSERT INTO characters VALUES (375,'Egyptian','Egyptian','');
INSERT INTO characters VALUES (376,'Elbow','ELBOW','a simple constable');
INSERT INTO characters VALUES (377,'Eleanor','DUCHESS','duchess of Gloucester');
INSERT INTO characters VALUES (378,'Bishop of Ely','ELY','');
INSERT INTO characters VALUES (379,'Emilia','EMILIA','Wife to Iago');
INSERT INTO characters VALUES (380,'Emilia','EMILIA','a lady attending on Hermione');
INSERT INTO characters VALUES (381,'English Herald','English Herald','');
INSERT INTO characters VALUES (382,'Eros','EROS','friend to Antony');
INSERT INTO characters VALUES (383,'Sir Thomas Erpingham','ERPINGHAM','');
INSERT INTO characters VALUES (384,'Prince Escalus','PRINCE','Prince of Verona');
INSERT INTO characters VALUES (385,'Escalus','ESCALUS','Escalus');
INSERT INTO characters VALUES (386,'Escanes','ESCANES','a lord of Tyre');
INSERT INTO characters VALUES (387,'Essex','ESSEX','earl of Essex');
INSERT INTO characters VALUES (388,'Euphronius','EUPHRONIUS','an ambassador from Antony to Caesar');
INSERT INTO characters VALUES (389,'Duke of Exeter','EXETER','uncle to Henry IV, great-uncle to Henry V');
INSERT INTO characters VALUES (390,'Sir Pierce of Exton','EXTON','');
INSERT INTO characters VALUES (391,'Fabian','FABIAN','servant to Olivia');
INSERT INTO characters VALUES (392,'Fairy','Fairy','');
INSERT INTO characters VALUES (393,'Falstaff','FALSTAFF','Sir John Falstaff');
INSERT INTO characters VALUES (394,'Fang','FANG','a Sheriff''s officer');
INSERT INTO characters VALUES (395,'Father','Father','who has killed his son');
INSERT INTO characters VALUES (396,'Faulconbridge','ROBERT','son of Sir Robert Faulconbridge');
INSERT INTO characters VALUES (397,'Francis Feeble','FEEBLE','country soldier');
INSERT INTO characters VALUES (398,'Fenton','FENTON','a gentleman');
INSERT INTO characters VALUES (399,'Ferdinand','FERDINAND','king of Navarre');
INSERT INTO characters VALUES (400,'Ferdinand','FERDINAND','son to the King of Naples');
INSERT INTO characters VALUES (401,'Feste','Clown','a clown, servant to Olivia');
INSERT INTO characters VALUES (402,'Fifth Citizen','Fifth Citizen','');
INSERT INTO characters VALUES (403,'First Ambassador','First Ambassador','');
INSERT INTO characters VALUES (404,'First Attendant','First Attendant','');
INSERT INTO characters VALUES (405,'First Bandit','First Bandit','');
INSERT INTO characters VALUES (406,'First Brother','First Brother','an apparition');
INSERT INTO characters VALUES (407,'First British Captain','First Captain','');
INSERT INTO characters VALUES (408,'First Carrier','First Carrier','');
INSERT INTO characters VALUES (409,'First Citizen','First Citizen','');
INSERT INTO characters VALUES (410,'First Citizen','First Citizen','');
INSERT INTO characters VALUES (411,'First Citizen','First Citizen','');
INSERT INTO characters VALUES (412,'First Citizen','First Citizen','');
INSERT INTO characters VALUES (413,'First Citizen','First Citizen','');
INSERT INTO characters VALUES (414,'First Commoner','First Commoner','');
INSERT INTO characters VALUES (415,'First Executioner','First Executioner','');
INSERT INTO characters VALUES (416,'First Fisherman','First Fisherman','');
INSERT INTO characters VALUES (417,'First Gaoler','First Gaoler','');
INSERT INTO characters VALUES (418,'First Gaoler','First Gaoler','');
INSERT INTO characters VALUES (419,'First Gentleman','First Gentleman','');
INSERT INTO characters VALUES (420,'First Gentleman','First Gentleman','');
INSERT INTO characters VALUES (421,'First Gentleman','First Gentleman','a gentleman of Cymbeline''s court');
INSERT INTO characters VALUES (422,'First Gentleman','First Gentleman','');
INSERT INTO characters VALUES (423,'First Gentleman','First Gentleman','');
INSERT INTO characters VALUES (424,'First Gentleman','First Gentleman','');
INSERT INTO characters VALUES (425,'First Gentleman','First Gentleman','');
INSERT INTO characters VALUES (426,'First Guard','First Guard','');
INSERT INTO characters VALUES (427,'First Herald','First Herald','');
INSERT INTO characters VALUES (428,'First Keeper','First Keeper','');
INSERT INTO characters VALUES (429,'First Knight','First Knight','');
INSERT INTO characters VALUES (430,'First Lady','First Lady','');
INSERT INTO characters VALUES (431,'First Lady','First Lady','');
INSERT INTO characters VALUES (432,'First Lady','First Lady','');
INSERT INTO characters VALUES (433,'First Lord','First Lord','');
INSERT INTO characters VALUES (434,'First Lord','First Lord','');
INSERT INTO characters VALUES (435,'First Lord','FIRST LORD','');
INSERT INTO characters VALUES (436,'First Lord','First Lord','a lord of Cymbeline''s court');
INSERT INTO characters VALUES (437,'First Lord','First Lord','');
INSERT INTO characters VALUES (438,'First Lord','First Lord','');
INSERT INTO characters VALUES (439,'First Lord','First Lord','');
INSERT INTO characters VALUES (440,'First Lord','First Lord','');
INSERT INTO characters VALUES (441,'First Merchant','First Merchant','friend to Antipholus of Syracuse');
INSERT INTO characters VALUES (442,'First Messenger','First Messenger','');
INSERT INTO characters VALUES (443,'First Murderer','First Murderer','');
INSERT INTO characters VALUES (444,'First Murderer','First Murderer','');
INSERT INTO characters VALUES (445,'First Neighbour','First Neighbour','');
INSERT INTO characters VALUES (446,'First Officer','First Officer','');
INSERT INTO characters VALUES (447,'First Officer','First Officer','');
INSERT INTO characters VALUES (448,'First Officer','First Officer','');
INSERT INTO characters VALUES (449,'First Outlaw','First Outlaw','');
INSERT INTO characters VALUES (450,'First Petitioner','First Petitioner','');
INSERT INTO characters VALUES (451,'First Pirate','First Pirate','');
INSERT INTO characters VALUES (452,'First ''Prentice','First ''Prentice','');
INSERT INTO characters VALUES (453,'First Roman','First Roman','');
INSERT INTO characters VALUES (454,'First Sailor','First Sailor','');
INSERT INTO characters VALUES (455,'First Secretary','First Secretary','to Wolsey');
INSERT INTO characters VALUES (456,'First Senator','First Senator','');
INSERT INTO characters VALUES (457,'First Senator','First Senator','');
INSERT INTO characters VALUES (458,'First Sentinel','First Sentinel','');
INSERT INTO characters VALUES (459,'First Servant','First Servant','');
INSERT INTO characters VALUES (460,'First Servant','First Servant','');
INSERT INTO characters VALUES (461,'First Servant','First Servant','');
INSERT INTO characters VALUES (462,'First Servant','First Servant','');
INSERT INTO characters VALUES (463,'First Servant','First Servant','');
INSERT INTO characters VALUES (464,'First Serviceman','First Serviceman','');
INSERT INTO characters VALUES (465,'First Servingman','First Servingman','');
INSERT INTO characters VALUES (466,'First Soldier','First Soldier','');
INSERT INTO characters VALUES (467,'First Soldier','First Soldier','');
INSERT INTO characters VALUES (468,'First Soldier','First Soldier','');
INSERT INTO characters VALUES (469,'First Soldier','First Soldier','');
INSERT INTO characters VALUES (470,'First Stranger','First Stranger','');
INSERT INTO characters VALUES (471,'First Traveller','First Traveller','');
INSERT INTO characters VALUES (472,'First Tribune','First Tribune','');
INSERT INTO characters VALUES (473,'First Warder','First Warder','');
INSERT INTO characters VALUES (474,'First Watchman','First Watchman','');
INSERT INTO characters VALUES (475,'Flaminius','Flaminius','');
INSERT INTO characters VALUES (476,'Flavius','FLAVIUS','steward to Timon');
INSERT INTO characters VALUES (477,'Flavius','FLAVIUS','a tribune');
INSERT INTO characters VALUES (478,'Fleance','FLEANCE','Son to Banquo');
INSERT INTO characters VALUES (479,'Florizel','FLORIZEL','prince of Bohemia');
INSERT INTO characters VALUES (480,'Fluellen','FLUELLEN','');
INSERT INTO characters VALUES (481,'Flute','FLUTE','a bellows-mender');
INSERT INTO characters VALUES (482,'Fool','Fool','');
INSERT INTO characters VALUES (483,'Fool','Fool','');
INSERT INTO characters VALUES (484,'Ford','FORD','a gentleman dwelling at Windsor');
INSERT INTO characters VALUES (485,'Forester','Forester','');
INSERT INTO characters VALUES (486,'Fortinbras','Fort','Prince of Norway');
INSERT INTO characters VALUES (487,'Fourth Citizen','Fourth Citizen','');
INSERT INTO characters VALUES (488,'Fourth Citizen','Fourth Citizen','');
INSERT INTO characters VALUES (489,'Fourth Lord','Fourth Lord','');
INSERT INTO characters VALUES (490,'Fourth Lord','Fourth Lord','');
INSERT INTO characters VALUES (491,'Fourth Messenger','Fourth Messenger','');
INSERT INTO characters VALUES (492,'Fourth Soldier','Fourth Soldier','');
INSERT INTO characters VALUES (493,'Francisca','FRANCISCA','a nun');
INSERT INTO characters VALUES (494,'Francisco','Fran','a soldier');
INSERT INTO characters VALUES (495,'Francisco','FRANCISCO','a lord');
INSERT INTO characters VALUES (496,'Francis','FRANCIS','a drawer');
INSERT INTO characters VALUES (497,'Frederick','FREDERICK','the Duke''s brother, and usurper of his dominions');
INSERT INTO characters VALUES (498,'French Herald','French Herald','');
INSERT INTO characters VALUES (499,'King of France','FRENCH KING','Charles VI');
INSERT INTO characters VALUES (500,'Frenchman','Frenchman','friend to Philario');
INSERT INTO characters VALUES (501,'French Soldier','French Soldier','');
INSERT INTO characters VALUES (502,'Friar Francis','FRIAR FRANCIS','');
INSERT INTO characters VALUES (503,'Friar John','FRIAR JOHN','Franciscan friar');
INSERT INTO characters VALUES (504,'Friar Laurence','FRIAR LAURENCE','Franciscan friar');
INSERT INTO characters VALUES (505,'Friar Peter','FRIAR PETER','');
INSERT INTO characters VALUES (506,'Friar Thomas','FRIAR THOMAS','');
INSERT INTO characters VALUES (507,'Froth','FROTH','a foolish gentleman');
INSERT INTO characters VALUES (508,'Gadshill','Gadshill','');
INSERT INTO characters VALUES (509,'Gallus','GALLUS','friend to Caesar');
INSERT INTO characters VALUES (510,'Gaoler','Gaoler','');
INSERT INTO characters VALUES (511,'Gaoler','Gaoler','');
INSERT INTO characters VALUES (512,'Gardener','Gardener','');
INSERT INTO characters VALUES (513,'Gardiner','GARDINER','bishop of Winchester');
INSERT INTO characters VALUES (514,'Garter','Garter','King-at-Arms');
INSERT INTO characters VALUES (515,'Host','Host','host of the Garter Inn');
INSERT INTO characters VALUES (516,'General','General','of the French forces in Bordeaux');
INSERT INTO characters VALUES (517,'Gentleman','Gentleman','');
INSERT INTO characters VALUES (518,'Gentleman','Gentleman','');
INSERT INTO characters VALUES (519,'Gentleman','Gent','');
INSERT INTO characters VALUES (520,'Gentleman','Gentleman','');
INSERT INTO characters VALUES (521,'Gentleman','Gentleman','');
INSERT INTO characters VALUES (522,'Gentleman','Gentleman','');
INSERT INTO characters VALUES (523,'Gentlemen','GENTLEMEN','');
INSERT INTO characters VALUES (524,'Gentlewoman','Gentlewoman','attending on Virgilia');
INSERT INTO characters VALUES (525,'Gentlewoman','Gentlewoman','');
INSERT INTO characters VALUES (526,'Gentlemen','Gentlemen','');
INSERT INTO characters VALUES (527,'George Plantagenet (Duke of Clarence)', 'GEORGE', '');
INSERT INTO characters VALUES (528,'Gertrude','Queen','Queen of Denmark and mother to Hamlet');
INSERT INTO characters VALUES (529,'Girl','Girl','');
INSERT INTO characters VALUES (530,'Glendower','GLENDOWER','');
INSERT INTO characters VALUES (531,'Duke of Gloucester','GLOUCESTER','brother to the King');
INSERT INTO characters VALUES (532,'Earl of Glouchester','Glou','');
INSERT INTO characters VALUES (533,'Goneril','Gon','daughter to Lear');
INSERT INTO characters VALUES (534,'Gonzalo','GONZALO','an honest old counsellor');
INSERT INTO characters VALUES (535,'Governor of Harfleur','GOVERNOR','');
INSERT INTO characters VALUES (536,'Gower','GOWER','');
INSERT INTO characters VALUES (537,'Gower','GOWER','as chorus');
INSERT INTO characters VALUES (538,'Grandpre','GRANDPRE','French lord');
INSERT INTO characters VALUES (539,'Gratiano','GRATIANO','Brother to Brabantio');
INSERT INTO characters VALUES (540,'Gratiano','GRATIANO','friend to Antonio and Bassiano');
INSERT INTO characters VALUES (541,'Green','GREEN','servant to King Richard II');
INSERT INTO characters VALUES (542,'Gregory','GREGORY','Servant to Gregory');
INSERT INTO characters VALUES (543,'Gremio','GREMIO','');
INSERT INTO characters VALUES (544,'Sir Thomas Grey','GREY','');
INSERT INTO characters VALUES (545,'Griffith','GRIFFITH','gentleman-usher to Queen Katherine');
INSERT INTO characters VALUES (546,'Groom','Groom','');
INSERT INTO characters VALUES (547,'First Groom','FIRST GROOM','');
INSERT INTO characters VALUES (548,'Second Groom','SECOND GROOM','');
INSERT INTO characters VALUES (549,'Third Groom','THIRD GROOM','');
INSERT INTO characters VALUES (550,'Grumio','GRUMIO','Petruchio''s man');
INSERT INTO characters VALUES (551,'Guard','Guard','');
INSERT INTO characters VALUES (552,'Guiderius','GUIDERIUS','son to Cymbeline, disguised under the name of Polydote, supposed son to Morgan');
INSERT INTO characters VALUES (553,'Guildenstern','Guil','courtier');
INSERT INTO characters VALUES (554,'Sir Henry Guildford','GUILDFORD','');
INSERT INTO characters VALUES (555,'James Gurney','GURNEY','servant to Lady Faulconbridge');
INSERT INTO characters VALUES (556,'Haberdasher','HABERDASHER','');
INSERT INTO characters VALUES (557,'Gentleman','Gent','courtier');
INSERT INTO characters VALUES (558,'Father''s Ghost','Ghost','Ghost of Hamlet''s Father');
INSERT INTO characters VALUES (559,'Hamlet','Ham','son of the former king and nephew to the present king');
INSERT INTO characters VALUES (560,'Players','','');
INSERT INTO characters VALUES (561,'Priest','Priest','');
INSERT INTO characters VALUES (562,'Harcourt','HARCOURT','');
INSERT INTO characters VALUES (563,'Lord Hastings','HASTINGS','');
INSERT INTO characters VALUES (564,'Hecate','HECATE','');
INSERT INTO characters VALUES (565,'Hector','HECTOR','son of Priam, king of Troy');
INSERT INTO characters VALUES (566,'Helen','HELEN','wife to Menelaus');
INSERT INTO characters VALUES (567,'Helena','HELENA','a gentlewoman protected by the Countess');
INSERT INTO characters VALUES (568,'Helena','HELENA','in love with Demetrius');
INSERT INTO characters VALUES (569,'Helen','HELEN','a lady attending on Cymbeline');
INSERT INTO characters VALUES (570,'Helenus','HELENUS','son of Priam, king of Troy');
INSERT INTO characters VALUES (571,'Helicanus','HELICANUS','a lord of Tyre');
INSERT INTO characters VALUES (572,'Henry IV','KING HENRY IV','King of England');
INSERT INTO characters VALUES (573,'Henry V','HENRY5','Prince, King of England');
INSERT INTO characters VALUES (574,'Henry VI','KING HENRY VI','');
INSERT INTO characters VALUES (575,'Richmond (Henry VII)', 'King Henry VII', 'Earl of Richmond, later Henry VII');
INSERT INTO characters VALUES (576,'Henry VIII','KING HENRY VIII','');
INSERT INTO characters VALUES (577,'Winchester','BISHOP OF WINCHESTER','Henry Beaufort, great-uncle to Henry V, bishop of Winchster, and later cardinal');
INSERT INTO characters VALUES (578,'Herald','Herald','');
INSERT INTO characters VALUES (579,'Herald','Herald','');
INSERT INTO characters VALUES (580,'Herald','Herald','');
INSERT INTO characters VALUES (581,'Herald','Her','');
INSERT INTO characters VALUES (582,'Herald','Herald','');
INSERT INTO characters VALUES (583,'Hermia','HERMIA','daughter to Egeus, in love with Lysander');
INSERT INTO characters VALUES (584,'Hermione','HERMIONE','queen to Leontes');
INSERT INTO characters VALUES (585,'Hero','HERO','Daughter to Leonato');
INSERT INTO characters VALUES (586,'Hippolyta','HIPPOLYTA','queen of the Amazons, betrothed to Theseus');
INSERT INTO characters VALUES (587,'Holofernes','HOLOFERNES','a schoolmaster');
INSERT INTO characters VALUES (588,'Horatio','Hor','friend to Hamlet');
INSERT INTO characters VALUES (589,'Hortensio','HORTENSIO','');
INSERT INTO characters VALUES (590,'Hortensius','HORTENSIUS','');
INSERT INTO characters VALUES (591,'Host','Host','where Julia lodges');
INSERT INTO characters VALUES (592,'Hostess','HOSTESS','');
INSERT INTO characters VALUES (593,'Hotspur (Henry Percy)', 'HOTSPUR', '');
INSERT INTO characters VALUES (594,'Hubert de Burgh','HUBERT','');
INSERT INTO characters VALUES (595,'Huntsman','Huntsman','');
INSERT INTO characters VALUES (596,'First Huntsman','FIRST HUNTSMAN','');
INSERT INTO characters VALUES (597,'Second Huntsman','SECOND HUNTSMAN','');
INSERT INTO characters VALUES (598,'Hymen','HYMEN','');
INSERT INTO characters VALUES (599,'Iachimo','IACHIMO','friend to Philario, an Italian.');
INSERT INTO characters VALUES (600,'Iago','IAGO','Othello''s ancient (?)');
INSERT INTO characters VALUES (601,'Imogen','IMOGEN','daughter to Cymbeline by a former queen');
INSERT INTO characters VALUES (602,'Iras','IRAS','attendant on Cleopatra');
INSERT INTO characters VALUES (603,'Iris','IRIS','presented by spirits');
INSERT INTO characters VALUES (604,'Queen Isabel','QUEEN ISABEL','');
INSERT INTO characters VALUES (605,'Isabella','ISABELLA','sister to Claudio');
INSERT INTO characters VALUES (606,'Jack Cade','CADE','a rebel');
INSERT INTO characters VALUES (607,'Jamy','JAMY','');
INSERT INTO characters VALUES (608,'Jaquenetta','JAQUENETTA','a country wench');
INSERT INTO characters VALUES (609,'Jaques (lord)', 'JAQUES', e'the Duke''s brother, and usurper of his dominions');
INSERT INTO characters VALUES (610,'Jaques (son)', 'JAQUES DE BOYS', e'the Duke''s brother, and usurper of his dominions');
INSERT INTO characters VALUES (611,'Jessica','JESSICA','daughter to Shylock');
INSERT INTO characters VALUES (612,'Jeweller','Jeweller','');
INSERT INTO characters VALUES (613,'Joan la Pucelle','JOAN LA PUCELLE','commonly called Joan of Arc');
INSERT INTO characters VALUES (614,'John of Gaunt','JOHN OF GAUNT','duke of Lancaster, uncle to the king');
INSERT INTO characters VALUES (615,'John Holland','HOLLAND','a follower of Cade');
INSERT INTO characters VALUES (616,'Father John Hume','HUME','a priest');
INSERT INTO characters VALUES (617,'John Morton','BISHOP OF ELY','bishop of Ely');
INSERT INTO characters VALUES (618,'Father John Southwell','JOHN SOUTHWELL','a priest');
INSERT INTO characters VALUES (619,'Joseph','JOSEPH','a servingman');
INSERT INTO characters VALUES (620,'Margaret Jourdain','MARGARET JOURDAIN','a witch');
INSERT INTO characters VALUES (621,'Julia','JULIA','beloved of Proteus');
INSERT INTO characters VALUES (622,'Juliet','JULIET','Daughter to Capulet');
INSERT INTO characters VALUES (623,'Juliet','JULIET','beloved of Claudio');
INSERT INTO characters VALUES (624,'Caesar','CAESAR','(Julius Caesar)');
INSERT INTO characters VALUES (625,'Junius Brutus','BRUTUS','tribune of the people');
INSERT INTO characters VALUES (626,'Juno','JUNO','presented by spirits');
INSERT INTO characters VALUES (627,'Jupiter','Jupiter','');
INSERT INTO characters VALUES (628,'Justice','Justice','');
INSERT INTO characters VALUES (629,'Katharine','KATHARINE','daughter to Charles and Isabel');
INSERT INTO characters VALUES (630,'Katharine','KATHARINE','lady attending on the princess');
INSERT INTO characters VALUES (631,'Katherina','KATHERINA','the shrew');
INSERT INTO characters VALUES (632,'Keeper','Keeper','');
INSERT INTO characters VALUES (633,'Keeper','Keeper','');
INSERT INTO characters VALUES (634,'Earl of Kent','','');
INSERT INTO characters VALUES (635,'King of France','KING','');
INSERT INTO characters VALUES (636,'King of France','France','');
INSERT INTO characters VALUES (637,'King John','KING JOHN','king of England');
INSERT INTO characters VALUES (638,'King Phillip','KING PHILIP','king of France');
INSERT INTO characters VALUES (639,'Knight','Knight','');
INSERT INTO characters VALUES (640,'Knights','Knights','');
INSERT INTO characters VALUES (641,'Lady Anne','LADY ANNE','widow of Edward Prince of Wales, son to King Henry VI; afterwards married to Richard III');
INSERT INTO characters VALUES (642,'Lady Capulet','LADY CAPULET','Wife to Capulet');
INSERT INTO characters VALUES (643,'Lady','Lady','');
INSERT INTO characters VALUES (644,'Lady Faulconbridge','LADY FAULCONBRIDGE','wife to Sir Robert Faulconbridge');
INSERT INTO characters VALUES (645,'Lady','Lady','attending on the Queen');
INSERT INTO characters VALUES (646,'Lady Macbeth','LADY MACBETH','');
INSERT INTO characters VALUES (647,'Lady Macduff','LADY MACDUFF','');
INSERT INTO characters VALUES (648,'Lady Montague','LADY MONTAGUE','Wife to Montague');
INSERT INTO characters VALUES (649,'Lady Northumberland','LADY NORTHUMBERLAND','');
INSERT INTO characters VALUES (650,'Lady Percy','LADY PERCY','');
INSERT INTO characters VALUES (651,'Laertes','Laer','son to Polonius');
INSERT INTO characters VALUES (652,'Lafeu','LAFEU','an old lord');
INSERT INTO characters VALUES (653,'John of Lancaster','','son of King Henry IV');
INSERT INTO characters VALUES (654,'Titus Lartius','TITUS','general against the Volscians');
INSERT INTO characters VALUES (655,'Launce','LAUNCE','the like to Proteus');
INSERT INTO characters VALUES (656,'Launcelot Gobbo','LAUNCELOT','the clown, servant to Shylock');
INSERT INTO characters VALUES (657,'Lavinia','LAVINIA','');
INSERT INTO characters VALUES (658,'Lawyer','Lawyer','');
INSERT INTO characters VALUES (659,'Lear','Lear','King of Britain');
INSERT INTO characters VALUES (660,'Le Beau','LE BEAU','a courtier attending upon Frederick');
INSERT INTO characters VALUES (661,'Legate','Legate','');
INSERT INTO characters VALUES (662,'Lennox','LENNOX','Nobleman of Scotland');
INSERT INTO characters VALUES (663,'Leonardo','LEONARDO','servant to Bassiano');
INSERT INTO characters VALUES (664,'Leonato','LEONATO','Governor of Messina');
INSERT INTO characters VALUES (665,'Sicilius Leonatus','Sicilius Leonatus','an apparition');
INSERT INTO characters VALUES (666,'Leonine','LEONINE','servant to Dionyza');
INSERT INTO characters VALUES (667,'Leontes','LEONTES','king of Sicilia');
INSERT INTO characters VALUES (668,'Lepidus','LEPIDUS','(Marcus Antonius Lepidus)');
INSERT INTO characters VALUES (669,'Lewis','LEWIS','the Dauphin');
INSERT INTO characters VALUES (670,'King Lewis XI','KING LEWIS XI','king of France');
INSERT INTO characters VALUES (671,'Lieutenant','LIEUTENANT','to Aufidius');
INSERT INTO characters VALUES (672,'Lieutenant','Lieutenant','of the Tower');
INSERT INTO characters VALUES (673,'Ligarius','LIGARIUS','a conspirator against Caesar');
INSERT INTO characters VALUES (674,'Lodovico','LODOVICO','Kinsman to Brabantio');
INSERT INTO characters VALUES (675,'Longaville','LONGAVILLE','lord attending on the king');
INSERT INTO characters VALUES (676,'Lord','LORD','');
INSERT INTO characters VALUES (677,'Lord Berkeley','LORD BERKELEY','');
INSERT INTO characters VALUES (678,'Lord Chamberlain','Chamberlain','');
INSERT INTO characters VALUES (679,'Lord Chancellor','Chancellor','');
INSERT INTO characters VALUES (680,'Lord Clifford','CLIFFORD','');
INSERT INTO characters VALUES (681,'Lord','Lord','');
INSERT INTO characters VALUES (682,'Lord Fitzwater','LORD FITZWATER','');
INSERT INTO characters VALUES (683,'Lord Grey','GREY','son of Queen Elizabeth');
INSERT INTO characters VALUES (684,'Lord','Lord','');
INSERT INTO characters VALUES (685,'Lord Hastings','HASTINGS','');
INSERT INTO characters VALUES (686,'Lord','Lord','');
INSERT INTO characters VALUES (687,'Lord Lovel','LOVEL','');
INSERT INTO characters VALUES (688,'Lord','Lord','');
INSERT INTO characters VALUES (689,'Lord','Lord','');
INSERT INTO characters VALUES (690,'Lord Marshal','LORD MARSHAL','');
INSERT INTO characters VALUES (691,'Lord','Lord','');
INSERT INTO characters VALUES (692,'Lord (Earl) Rivers', 'RIVERS', 'brother to Lady Gray (Queen Elizabeth)');
INSERT INTO characters VALUES (693,'Lord Sands','SANDS','');
INSERT INTO characters VALUES (694,'Lord Say','SAY','');
INSERT INTO characters VALUES (695,'Lord Scales','SCALES','');
INSERT INTO characters VALUES (696,'Lord Scroop','SCROOP','');
INSERT INTO characters VALUES (697,'Lords','Lords','');
INSERT INTO characters VALUES (698,'Lords','Lords','');
INSERT INTO characters VALUES (699,'Lords','LORDS','');
INSERT INTO characters VALUES (700,'Lord Stafford','STAFFORD','');
INSERT INTO characters VALUES (701,'Lords','Lords','');
INSERT INTO characters VALUES (702,'Lord','LORD','');
INSERT INTO characters VALUES (703,'Lord Willoughby','LORD WILLOUGHBY','');
INSERT INTO characters VALUES (704,'Lord','Lord','');
INSERT INTO characters VALUES (705,'Lorenzo','LORENZO','in love with Jessica');
INSERT INTO characters VALUES (706,'Sir Thomas Lovell','LOVELL','');
INSERT INTO characters VALUES (707,'Luce','LUCE','servant to Adriana');
INSERT INTO characters VALUES (708,'Lucentio','LUCENTIO','son to Vincentio, in love with Bianca');
INSERT INTO characters VALUES (709,'Lucetta','LUCETTA','waiting-woman to Julia');
INSERT INTO characters VALUES (710,'Luciana','LUCIANA','sister to Adriana');
INSERT INTO characters VALUES (711,'Lucianus','Luc','');
INSERT INTO characters VALUES (712,'Lucilius','LUCILIUS','servant to Timon');
INSERT INTO characters VALUES (713,'Lucilius','LUCILIUS','friend to Brutus');
INSERT INTO characters VALUES (714,'Lucilius'' Servant','Lucilius'' Servant','');
INSERT INTO characters VALUES (715,'Lucio','LUCIO','a fantastic');
INSERT INTO characters VALUES (716,'Lucius','LUCIUS','son to Titus Andronicus');
INSERT INTO characters VALUES (717,'Lucius','LUCIUS','servant to Brutus');
INSERT INTO characters VALUES (718,'Lucius','LUCIUS','flattering lord');
INSERT INTO characters VALUES (719,'Lucullus','LUCULLUS','flattering lord');
INSERT INTO characters VALUES (720,'Lychorida','LYCHORIDA','nurse to Marina');
INSERT INTO characters VALUES (721,'Lymoges','AUSTRIA','duke of Austria');
INSERT INTO characters VALUES (722,'Lysander','LYSANDER','in love with Hermia');
INSERT INTO characters VALUES (723,'Lysimachus','LYSIMACHUS','governor of Mytilene');
INSERT INTO characters VALUES (724,'Macbeth','MACBETH','General of the King''s army');
INSERT INTO characters VALUES (725,'Macduff','MACDUFF','Nobleman of Scotland');
INSERT INTO characters VALUES (726,'Macmorris','MACMORRIS','');
INSERT INTO characters VALUES (727,'Malcolm','MALCOLM','Son of Duncan');
INSERT INTO characters VALUES (728,'Malvolio','MALVOLIO','steward to Olivia');
INSERT INTO characters VALUES (729,'Mamillius','MAMILLIUS','young prince of Sicilia');
INSERT INTO characters VALUES (730,'Man','Man','the Porter''s man');
INSERT INTO characters VALUES (731,'Marcellus','Mar','Officer');
INSERT INTO characters VALUES (732,'Marcus Andronicus','MARCUS ANDRONICUS','tribune of the people, and brother to Titus');
INSERT INTO characters VALUES (733,'Mardian','MARDIAN','a eunuch, attendant on Cleopatra');
INSERT INTO characters VALUES (734,'Margarelon','MARGARELON','a bastard son of Priam');
INSERT INTO characters VALUES (735,'Margaret','MARGARET','Gentlewoman attending on Hero');
INSERT INTO characters VALUES (736,'Queen Margaret','Margaret','daughter to Reignier, afterwards married to King Henry VI');
INSERT INTO characters VALUES (737,'Margaret Plantagenet','MARGARET PLANTAGENET','a young daughter of Clarence');
INSERT INTO characters VALUES (738,'Maria','MARIA','Olivia''s woman');
INSERT INTO characters VALUES (739,'Maria','MARIA','lady attending on the princess');
INSERT INTO characters VALUES (740,'Mariana','MARIANA','neighbor and friend to the widow');
INSERT INTO characters VALUES (741,'Mariana','MARIANA','');
INSERT INTO characters VALUES (742,'Marina','MARINA','daughter to Pericles and Thaisa');
INSERT INTO characters VALUES (743,'Mariners','Mariners','');
INSERT INTO characters VALUES (744,'Mariner','Mariner','');
INSERT INTO characters VALUES (745,'Marquess of Montague','MONTAGUE','');
INSERT INTO characters VALUES (746,'Marquis of Dorset','DORSET','son of Queen Elizabeth');
INSERT INTO characters VALUES (747,'Marshal','Marshal','');
INSERT INTO characters VALUES (748,'Sir Oliver Martext','MARTEXT','a vicar');
INSERT INTO characters VALUES (749,'Martius','MARTIUS','son to Titus Andronicus');
INSERT INTO characters VALUES (750,'Marullus','MARULLUS','a tribune');
INSERT INTO characters VALUES (751,'Master','Master','');
INSERT INTO characters VALUES (752,'Master-Gunner','Master-Gunner','of Orleans');
INSERT INTO characters VALUES (753,'Master','Master','master of a ship');
INSERT INTO characters VALUES (754,'Matthew Goffe','MATTHEW GOFFE','');
INSERT INTO characters VALUES (755,'Mayor of Saint Alban''s','Mayor','');
INSERT INTO characters VALUES (756,'Lord Mayor of London','Mayor','');
INSERT INTO characters VALUES (757,'Mayor of York','Mayor','');
INSERT INTO characters VALUES (758,'Mecaenas','MECAENAS','friend to Caesar');
INSERT INTO characters VALUES (759,'Melun','MELUN','a French Lord');
INSERT INTO characters VALUES (760,'Menas','MENAS','friend to Caesar');
INSERT INTO characters VALUES (761,'Menecrates','MENECRATES','friend to Pompey');
INSERT INTO characters VALUES (762,'Menelaus','MENELAUS','Agamemnon''s brother');
INSERT INTO characters VALUES (763,'Menenius Agrippa','MENENIUS','friend to Coriolanus');
INSERT INTO characters VALUES (764,'Menteith','MENTEITH','Nobleman of Scotland');
INSERT INTO characters VALUES (765,'Mercade','MERCADE','lord attending on the princess of France');
INSERT INTO characters VALUES (766,'Merchant','Merchant','');
INSERT INTO characters VALUES (767,'Mercutio','MERCUTIO','Kinsman to Escalus the prince, and friend to Romeo');
INSERT INTO characters VALUES (768,'Messala','MESSALA','friend to Brutus');
INSERT INTO characters VALUES (769,'Messenger','Messenger','');
INSERT INTO characters VALUES (770,'Messenger','Messenger','');
INSERT INTO characters VALUES (771,'Messenger','Messenger','');
INSERT INTO characters VALUES (772,'Messenger','Messenger','');
INSERT INTO characters VALUES (773,'Messenger','MESSENGER','');
INSERT INTO characters VALUES (774,'Messenger','Messenger','');
INSERT INTO characters VALUES (775,'Messenger','Messenger','');
INSERT INTO characters VALUES (776,'Messenger','Messenger','');
INSERT INTO characters VALUES (777,'Messenger','Messenger','');
INSERT INTO characters VALUES (778,'Messenger','Messenger','');
INSERT INTO characters VALUES (779,'Messenger','Mess','');
INSERT INTO characters VALUES (780,'Messenger','Messenger','');
INSERT INTO characters VALUES (781,'Messenger','Messenger','');
INSERT INTO characters VALUES (782,'Messenger','Mess','');
INSERT INTO characters VALUES (783,'Messenger','Messenger','');
INSERT INTO characters VALUES (784,'Messenger','Messenger','');
INSERT INTO characters VALUES (785,'Messenger','Messenger','');
INSERT INTO characters VALUES (786,'Messenger','Messenger','');
INSERT INTO characters VALUES (787,'Messenger','Messenger','');
INSERT INTO characters VALUES (788,'Messenger','Messenger','');
INSERT INTO characters VALUES (789,'Messenger','Messenger','');
INSERT INTO characters VALUES (790,'Messenger','Messenger','');
INSERT INTO characters VALUES (791,'Messenger','MESSENGER','');
INSERT INTO characters VALUES (792,'Metellus Cimber','Metellus Cimber','a conspirator against Caesar');
INSERT INTO characters VALUES (793,'Michael','MICHAEL','a follower of Cade');
INSERT INTO characters VALUES (794,'Miranda','MIRANDA','daughter to Prospero');
INSERT INTO characters VALUES (795,'Mistress Ford','MISTRESS FORD','');
INSERT INTO characters VALUES (796,'Mistress Overdone','MISTRESS OVERDONE','a bawd');
INSERT INTO characters VALUES (797,'Mistress Page','MISTRESS PAGE','');
INSERT INTO characters VALUES (798,'Montague','MONTAGUE','Head of the house of Montague');
INSERT INTO characters VALUES (799,'Montano','MONTANO','Othello''s predecessor in the government of Cyprus');
INSERT INTO characters VALUES (800,'Montjoy','MONTJOY','a French herald');
INSERT INTO characters VALUES (801,'Mopsa','MOPSA','a shepherdess');
INSERT INTO characters VALUES (802,'Mortimer','MORTIMER','Earl of March');
INSERT INTO characters VALUES (803,'Morton','MORTON','retainer of Northumberland');
INSERT INTO characters VALUES (804,'Moth','MOTH','page to Armado');
INSERT INTO characters VALUES (805,'Mother','Mother','an apparition');
INSERT INTO characters VALUES (806,'Moth','MOTH','a fairy');
INSERT INTO characters VALUES (807,'Ralph Mouldy','MOULDY','country soldier');
INSERT INTO characters VALUES (808,'Lord Mowbray','MOWBRAY','');
INSERT INTO characters VALUES (809,'Mustardseed','MUSTARDSEED','a fairy');
INSERT INTO characters VALUES (810,'Mutius','MUTIUS','son to Titus Andronicus');
INSERT INTO characters VALUES (811,'Myrmidons','MYRMIDONS','soldiers of Achilles in the Trojan war');
INSERT INTO characters VALUES (812,'Nathaniel','NATHANIEL','a servingman');
INSERT INTO characters VALUES (813,'Nerissa','NERISSA','Portia''s maid-in-waiting');
INSERT INTO characters VALUES (814,'Nestor','NESTOR','a Greek prince');
INSERT INTO characters VALUES (815,'Nicholas','NICHOLAS','a servingman');
INSERT INTO characters VALUES (816,'Nobleman','Nobleman','');
INSERT INTO characters VALUES (817,'Norwegian Captain','Capt','');
INSERT INTO characters VALUES (818,'Nurse','Nurse','Nurse to Juliet');
INSERT INTO characters VALUES (819,'Nurse','Nurse','');
INSERT INTO characters VALUES (820,'Nym','NYM','sharper attending on Falstaff');
INSERT INTO characters VALUES (821,'Nymphs','Nymphs','presented by spirits');
INSERT INTO characters VALUES (822,'Oberon','OBERON','king of the fairies');
INSERT INTO characters VALUES (823,'Octavia','OCTAVIA','sister to Caesar and wife to Antony');
INSERT INTO characters VALUES (824,'Octavius','OCTAVIUS','(Octavius Caesar)');
INSERT INTO characters VALUES (825,'Officer','Officer','');
INSERT INTO characters VALUES (826,'Officer','Officer','');
INSERT INTO characters VALUES (827,'Officer','Officer','');
INSERT INTO characters VALUES (828,'Officer','Officer','');
INSERT INTO characters VALUES (829,'Old Athenian','Old Athenian','');
INSERT INTO characters VALUES (830,'Old Gobbo','GOBBO','father to Launcelot');
INSERT INTO characters VALUES (831,'Old Lady','Old Lady','friend to Anne Bullen');
INSERT INTO characters VALUES (832,'Old Man','Old Man','tenant to Glouchester');
INSERT INTO characters VALUES (833,'Old Man','Old Man','');
INSERT INTO characters VALUES (834,'Old Shepherd','Shepherd','reputed father of Perdita');
INSERT INTO characters VALUES (835,'Oliver','OLIVER','son of Sir Rowland de Boys');
INSERT INTO characters VALUES (836,'Olivia','OLIVIA','');
INSERT INTO characters VALUES (837,'Ophelia','Oph','daughter to Polonius');
INSERT INTO characters VALUES (838,'Orlando','ORLANDO','son of Sir Rowland de Boys');
INSERT INTO characters VALUES (839,'Duke of Orleans','ORLEANS','');
INSERT INTO characters VALUES (840,'Orsino','DUKE ORSINO','Duke of Illyria');
INSERT INTO characters VALUES (841,'Osric','Osr','courtier');
INSERT INTO characters VALUES (842,'Ostler','Ostler','');
INSERT INTO characters VALUES (843,'Oswald','Osw','steward to Goneril');
INSERT INTO characters VALUES (844,'Othello','OTHELLO','A noble Moor in the service of the Ventian state');
INSERT INTO characters VALUES (845,'Outlaws','Outlaws','');
INSERT INTO characters VALUES (846,'First Page','FIRST PAGE','');
INSERT INTO characters VALUES (847,'Second Page','SECOND PAGE','');
INSERT INTO characters VALUES (848,'Page','Page','');
INSERT INTO characters VALUES (849,'Page','PAGE','to Falstaff');
INSERT INTO characters VALUES (850,'Page','Boy','a page to Gardiner');
INSERT INTO characters VALUES (851,'Page','PAGE','a gentleman dwelling at Windsor');
INSERT INTO characters VALUES (852,'Page','Page','');
INSERT INTO characters VALUES (853,'Page','PAGE','Page to Paris');
INSERT INTO characters VALUES (854,'Page','Page','');
INSERT INTO characters VALUES (855,'Page','PAGE','');
INSERT INTO characters VALUES (856,'Painter','Painter','');
INSERT INTO characters VALUES (857,'Pandar','Pandar','');
INSERT INTO characters VALUES (858,'Pandarus','PANDARUS','uncle to Cressida');
INSERT INTO characters VALUES (859,'Panthino','PANTHINO','servant to Antonio');
INSERT INTO characters VALUES (860,'Paris','PARIS','A young nobleman, kinsman to Escalus the prince');
INSERT INTO characters VALUES (861,'Paris','PARIS','son of Priam, king of Troy');
INSERT INTO characters VALUES (862,'Parolles','PAROLLES','a follower of Bertram');
INSERT INTO characters VALUES (863,'Patience','PATIENCE','woman to Queen Katharine');
INSERT INTO characters VALUES (864,'Patrician','A Patrician','');
INSERT INTO characters VALUES (865,'Patroclus','PATROCLUS','a Greek prince');
INSERT INTO characters VALUES (866,'Paulina','PAULINA','wife to Antigonus');
INSERT INTO characters VALUES (867,'Peaseblossom','PEASEBLOSSOM','a fairy');
INSERT INTO characters VALUES (868,'Pedant','PEDANT','');
INSERT INTO characters VALUES (869,'Pembroke','PEMBROKE','earl of Pembroke');
INSERT INTO characters VALUES (870,'Earl of Pembroke','PEMBROKE','');
INSERT INTO characters VALUES (871,'Perdita','PERDITA','daughter to Leontes and Hermione');
INSERT INTO characters VALUES (872,'Pericles','PERICLES','prince of Tyre');
INSERT INTO characters VALUES (873,'Peter','PETER','Thomas Horner''s man');
INSERT INTO characters VALUES (874,'Peter of Pomfret','PETER','a prophet');
INSERT INTO characters VALUES (875,'Peter','PETER','Servant to Julet''s nurse');
INSERT INTO characters VALUES (876,'Peter','PETER','a servingman');
INSERT INTO characters VALUES (877,'Peto','PETO','');
INSERT INTO characters VALUES (878,'Petruchio','PETRUCHIO','a gentleman of Verona, a suitor to Katherina');
INSERT INTO characters VALUES (879,'Phebe','PHEBE','a shepherdess');
INSERT INTO characters VALUES (880,'Philario','PHILARIO','friend to Posthumus, an Italian.');
INSERT INTO characters VALUES (881,'Philemon','PHILEMON','servant to Cerimon');
INSERT INTO characters VALUES (882,'Philip the Bastard','BASTARD','illegitimate son of Sir Robert Faulconbridge');
INSERT INTO characters VALUES (883,'Philip','PHILIP','a servingman');
INSERT INTO characters VALUES (884,'Philo','PHILO','friend to Antony');
INSERT INTO characters VALUES (885,'Philostrate','PHILOSTRATE','master of the revels to Theseus');
INSERT INTO characters VALUES (886,'Philotus','PHILOTUS','servant to Timon''s creditors');
INSERT INTO characters VALUES (887,'Phrynia','PHRYNIA','mistress to Alcibiades');
INSERT INTO characters VALUES (888,'Pinch','PINCH','a schoolmaster');
INSERT INTO characters VALUES (889,'Pindarus','PINDARUS','servant to Cassius');
INSERT INTO characters VALUES (890,'Pisanio','PISANIO','servant to Posthumus');
INSERT INTO characters VALUES (891,'Pistol','PISTOL','');
INSERT INTO characters VALUES (892,'Players','PLAYERS','');
INSERT INTO characters VALUES (893,'Player','PLAYER','');
INSERT INTO characters VALUES (894,'Poet','Poet','the voice of Shakespeare''s poetry');
INSERT INTO characters VALUES (895,'Poet','Poet','');
INSERT INTO characters VALUES (896,'Poet','Poet','');
INSERT INTO characters VALUES (897,'Edward Poins','POINS','');
INSERT INTO characters VALUES (898,'Polixenes','POLIXENES','king of Bohemia');
INSERT INTO characters VALUES (899,'Polonius','Pol','Lord Chamberlain');
INSERT INTO characters VALUES (900,'Pompey','POMPEY','(Sextus Pompeius)');
INSERT INTO characters VALUES (901,'Pompey','POMPEY','servant to Mistress Overdone');
INSERT INTO characters VALUES (902,'Popilius','POPILIUS','(Popilius Lena)');
INSERT INTO characters VALUES (903,'Porter','PORTER','');
INSERT INTO characters VALUES (904,'Porter','Porter','');
INSERT INTO characters VALUES (905,'Porter','Porter','door-keeper of the Council-chamber');
INSERT INTO characters VALUES (906,'Porter','Porter','');
INSERT INTO characters VALUES (907,'Portia','PORTIA','wife to Brutus');
INSERT INTO characters VALUES (908,'Portia','PORTIA','a rich heiress');
INSERT INTO characters VALUES (909,'Post','Post','');
INSERT INTO characters VALUES (910,'Post','Post','');
INSERT INTO characters VALUES (911,'Posthumus Leonatus','POSTHUMUS LEONATUS','a gentleman, husband to Imogen');
INSERT INTO characters VALUES (912,'Priam','PRIAM','king of Troy');
INSERT INTO characters VALUES (913,'Priest','Priest','');
INSERT INTO characters VALUES (914,'Priest','Priest','');
INSERT INTO characters VALUES (915,'Prince of Arragon','ARRAGON','suitor to Portia');
INSERT INTO characters VALUES (916,'Prince Edward','PRINCE EDWARD','');
INSERT INTO characters VALUES (917,'Prince Henry','PRINCE HENRY','son to King John');
INSERT INTO characters VALUES (918,'Prince Humphrey','PRINCE HUMPHREY','of Goucester');
INSERT INTO characters VALUES (919,'Prince John','LANCASTER','of Lancaster');
INSERT INTO characters VALUES (920,'Prince of Morocco','MOROCCO','suitor to Portia');
INSERT INTO characters VALUES (921,'Princes','Princes','');
INSERT INTO characters VALUES (922,'Princess of France','PRINCESS','');
INSERT INTO characters VALUES (923,'Proculeius','PROCULEIUS','friend to Caesar');
INSERT INTO characters VALUES (924,'Prospero','PROSPERO','the rightful Duke of Milan');
INSERT INTO characters VALUES (925,'Proteus','PROTEUS','a gentleman');
INSERT INTO characters VALUES (926,'Provost','Provost','');
INSERT INTO characters VALUES (927,'Publius','PUBLIUS','son to Marcus the Tribune');
INSERT INTO characters VALUES (928,'Publius','PUBLIUS','Senator');
INSERT INTO characters VALUES (929,'Puck','PUCK','or Robin Goodfellow');
INSERT INTO characters VALUES (930,'Pursuivant','Pursuivant','');
INSERT INTO characters VALUES (931,'Queen','QUEEN','wife to Cymbeline');
INSERT INTO characters VALUES (932,'Queen Elinor','QUEEN ELINOR','mother to King John');
INSERT INTO characters VALUES (933,'Queen Elizabeth','QUEEN ELIZABETH','starts as Lady Grey, marries Edward IV');
INSERT INTO characters VALUES (934,'Queen Katharine','QUEEN KATHARINE','wife to King Henry, afterwards divorced');
INSERT INTO characters VALUES (935,'Queen','QUEEN','');
INSERT INTO characters VALUES (936,'Hostess Quickly','HOSTESS','hostess of a tavern in Eastcheap');
INSERT INTO characters VALUES (937,'Quince','QUINCE','a carpenter');
INSERT INTO characters VALUES (938,'Quintus','QUINTUS','son to Titus Andronicus');
INSERT INTO characters VALUES (939,'Rambures','RAMBURES','French lord');
INSERT INTO characters VALUES (940,'Reapers','Reapers','presented by spirits');
INSERT INTO characters VALUES (941,'Regan','Reg','daughter to Lear');
INSERT INTO characters VALUES (942,'Reignier','REIGNIER','duke of Anjou, and titular king of Naples');
INSERT INTO characters VALUES (943,'Reynaldo','Rey','servant to Polonius');
INSERT INTO characters VALUES (944,'King Richard II','KING RICHARD II','king of England');
INSERT INTO characters VALUES (945,'Richard III','RICHARD3','son of Richard Plantagenet, duke of York; was duke of Gloucester before enthronement');
INSERT INTO characters VALUES (946,'Richard Plantagenet (Duke of Gloucester)', 'PLANTAGENET', 'becomes duke of York in Henry VI, Part');
INSERT INTO characters VALUES (947,'Richard Plantagenet the Younger','RICHARD','');
INSERT INTO characters VALUES (948,'Robin','ROBIN','page to Falstaff');
INSERT INTO characters VALUES (949,'Roderigo','RODERIGO','A Venetian gentleman');
INSERT INTO characters VALUES (950,'Roman Captain','Captain','');
INSERT INTO characters VALUES (951,'Roman','Roman','');
INSERT INTO characters VALUES (952,'Romeo','ROMEO','Son to Montague');
INSERT INTO characters VALUES (953,'Rosalind','ROSALIND','daughter to the banished Duke');
INSERT INTO characters VALUES (954,'Rosaline','ROSALINE','lady attending on the princess');
INSERT INTO characters VALUES (955,'Rosencrantz','Ros','courtier');
INSERT INTO characters VALUES (956,'Ross','ROSS','Nobleman of Scotland');
INSERT INTO characters VALUES (957,'Lord Ross','LORD ROSS','');
INSERT INTO characters VALUES (958,'Rugby','RUGBY','servant to Doctor Caius');
INSERT INTO characters VALUES (959,'Rumour','RUMOUR','the Presenter');
INSERT INTO characters VALUES (960,'Sailor','Sailor','');
INSERT INTO characters VALUES (961,'Sailor','Sailor','');
INSERT INTO characters VALUES (962,'Salanio','SALANIO','friend to Antonio and Bassiano');
INSERT INTO characters VALUES (963,'Salarino','SALARINO','friend to Antonio and Bassiano');
INSERT INTO characters VALUES (964,'Salerio','SALERIO','friend to Antonio and Bassiano');
INSERT INTO characters VALUES (965,'Earl of Salisbury','SALISBURY','');
INSERT INTO characters VALUES (966,'Salisbury','SALISBURY','earl of Salisbury');
INSERT INTO characters VALUES (967,'Earl of Salisbury','EARL OF SALISBURY','');
INSERT INTO characters VALUES (968,'Sampson','SAMPSON','Servant to Capulet');
INSERT INTO characters VALUES (969,'Saturninus','SATURNINUS','son to the late Emperor of Rome, and afterwards\r\n	declared Emperor');
INSERT INTO characters VALUES (970,'Scarus','SCARUS','friend to Antony');
INSERT INTO characters VALUES (971,'Scout','Scout','');
INSERT INTO characters VALUES (972,'Scribe','Scribe','');
INSERT INTO characters VALUES (973,'Scrivener','Scrivener','');
INSERT INTO characters VALUES (974,'Archbishop Scroop','ARCHBISHOP','Archbishop of York');
INSERT INTO characters VALUES (975,'Captain','Captain','friend to Viola');
INSERT INTO characters VALUES (976,'Sebastian','SEBASTIAN','brother to Viola');
INSERT INTO characters VALUES (977,'Sebastian','SEBASTIAN','the King''s brother');
INSERT INTO characters VALUES (978,'Second Attendant','Second Attendant','');
INSERT INTO characters VALUES (979,'Second Bandit','Second Bandit','');
INSERT INTO characters VALUES (980,'Second Brother','Second Brother','an apparition');
INSERT INTO characters VALUES (981,'Second British Captain','Second Captain','');
INSERT INTO characters VALUES (982,'Second Carrier','Second Carrier','');
INSERT INTO characters VALUES (983,'Second Citizen','Second Citizen','');
INSERT INTO characters VALUES (984,'Second Citizen','Second Citizen','');
INSERT INTO characters VALUES (985,'Second Citizen','Second Citizen','');
INSERT INTO characters VALUES (986,'Second Commoner','Second Commoner','');
INSERT INTO characters VALUES (987,'Second Fisherman','Second Fisherman','');
INSERT INTO characters VALUES (988,'Second Gaoler','Second Gaoler','');
INSERT INTO characters VALUES (989,'Second Gentleman','Second Gentleman','');
INSERT INTO characters VALUES (990,'Second Gentleman','Second Gentleman','');
INSERT INTO characters VALUES (991,'Second Gentleman','Second Gentleman','a gentleman of Cymbeline''s court');
INSERT INTO characters VALUES (992,'Second Gentleman','Second Gentleman','');
INSERT INTO characters VALUES (993,'Second Gentleman','Second Gentleman','');
INSERT INTO characters VALUES (994,'Second Gentleman','Second Gentleman','');
INSERT INTO characters VALUES (995,'Second Gentleman','Second Gentleman','');
INSERT INTO characters VALUES (996,'Second Guard','Second Guard','');
INSERT INTO characters VALUES (997,'Second Herald','Second Herald','');
INSERT INTO characters VALUES (998,'Second Keeper','Second Keeper','');
INSERT INTO characters VALUES (999,'Second Knight','Second Knight','');
INSERT INTO characters VALUES (1000,'Second Lady','Second Lady','');
INSERT INTO characters VALUES (1001,'Second Lord','Second Lord','');
INSERT INTO characters VALUES (1002,'Second Lord','Second Lord','');
INSERT INTO characters VALUES (1003,'Second Lord','SECOND LORD','');
INSERT INTO characters VALUES (1004,'Second Lord','Second Lord','a lord of Cymbeline''s court');
INSERT INTO characters VALUES (1005,'Second Lord','Second Lord','');
INSERT INTO characters VALUES (1006,'Second Lord','Second Lord','');
INSERT INTO characters VALUES (1007,'Second Merchant','Second Merchant','indebted to Angelo');
INSERT INTO characters VALUES (1008,'Second Messenger','Second Messenger','');
INSERT INTO characters VALUES (1009,'Second Messenger','Second Messenger','');
INSERT INTO characters VALUES (1010,'Second Messenger','Second Messenger','');
INSERT INTO characters VALUES (1011,'Second Messenger','Second Messenger','');
INSERT INTO characters VALUES (1012,'Second Murderer','Second Murderer','');
INSERT INTO characters VALUES (1013,'Second Murderer','Second Murderer','');
INSERT INTO characters VALUES (1014,'Second Neighbour','Second Neighbour','');
INSERT INTO characters VALUES (1015,'Second Officer','Second Officer','');
INSERT INTO characters VALUES (1016,'Second Officer','Second Officer','');
INSERT INTO characters VALUES (1017,'Second Officer','Second Officer','');
INSERT INTO characters VALUES (1018,'Second Outlaw','Second Outlaw','');
INSERT INTO characters VALUES (1019,'Second Petitioner','Second Petitioner','');
INSERT INTO characters VALUES (1020,'Second Pirate','Second Pirate','');
INSERT INTO characters VALUES (1021,'Second ''Prentice','Second ''Prentice','');
INSERT INTO characters VALUES (1022,'Second Roman','Second Roman','');
INSERT INTO characters VALUES (1023,'Second Sailor','Second Sailor','');
INSERT INTO characters VALUES (1024,'Second Secretary','Second Secretary','to Wolsey');
INSERT INTO characters VALUES (1025,'Second Senator','Second Senator','');
INSERT INTO characters VALUES (1026,'Second Senator','Second Senator','');
INSERT INTO characters VALUES (1027,'Second Sentinel','Second Sentinel','');
INSERT INTO characters VALUES (1028,'Second Servant','Second Servant','');
INSERT INTO characters VALUES (1029,'Second Servant','Second Servant','');
INSERT INTO characters VALUES (1030,'Second Servant','Second Servant','');
INSERT INTO characters VALUES (1031,'Second Servant','Second Servant','');
INSERT INTO characters VALUES (1032,'Second Serviceman','Second Serviceman','');
INSERT INTO characters VALUES (1033,'Second Servingman','Second Servingman','');
INSERT INTO characters VALUES (1034,'Second Soldier','Second Soldier','');
INSERT INTO characters VALUES (1035,'Second Soldier','Second Soldier','');
INSERT INTO characters VALUES (1036,'Second Soldier','Second Soldier','');
INSERT INTO characters VALUES (1037,'Second Stranger','Second Stranger','');
INSERT INTO characters VALUES (1038,'Second Warder','Second Warder','');
INSERT INTO characters VALUES (1039,'Second Watchman','Second Watchman','');
INSERT INTO characters VALUES (1040,'Seleucus','SELEUCUS','attendant on Cleopatra');
INSERT INTO characters VALUES (1041,'Sempronius','SEMPRONIUS','kinsman to Titus');
INSERT INTO characters VALUES (1042,'Sempronius','SEMPRONIUS','flattering lord');
INSERT INTO characters VALUES (1043,'Senator','','A senator of Venice');
INSERT INTO characters VALUES (1044,'Senator','Senator','');
INSERT INTO characters VALUES (1045,'Sentinels','Sentinels','');
INSERT INTO characters VALUES (1046,'Sergeant','Sergeant','');
INSERT INTO characters VALUES (1047,'Sergeant','Sergeant','a sergeant-at-arms');
INSERT INTO characters VALUES (1048,'Sergeant','Sergeant','');
INSERT INTO characters VALUES (1049,'Servant','Servant','servant to Diomedes');
INSERT INTO characters VALUES (1050,'Servant','Servant','');
INSERT INTO characters VALUES (1051,'Servant 1','Serv1','');
INSERT INTO characters VALUES (1052,'First Servant','FIRST SERVANT','');
INSERT INTO characters VALUES (1053,'Servant 2','Serv2','');
INSERT INTO characters VALUES (1054,'Second Servant','SECOND SERVANT','');
INSERT INTO characters VALUES (1055,'Servant 3','Serv3','');
INSERT INTO characters VALUES (1056,'Third Servant','THIRD SERVANT','');
INSERT INTO characters VALUES (1057,'Servant','Servant','');
INSERT INTO characters VALUES (1058,'Servant','Servant','');
INSERT INTO characters VALUES (1059,'Servant','Servant','');
INSERT INTO characters VALUES (1060,'Servant','SERVANT','');
INSERT INTO characters VALUES (1061,'Servant','Servant','');
INSERT INTO characters VALUES (1062,'Servant','Servant','');
INSERT INTO characters VALUES (1063,'Servant','Servant','');
INSERT INTO characters VALUES (1064,'Servant','Servant','');
INSERT INTO characters VALUES (1065,'Servant','Servant','');
INSERT INTO characters VALUES (1066,'Servant','Servant','');
INSERT INTO characters VALUES (1067,'Servant','Servant','');
INSERT INTO characters VALUES (1068,'Servant','Servant','');
INSERT INTO characters VALUES (1069,'Servant','Servant','');
INSERT INTO characters VALUES (1070,'Servant','Servant','');
INSERT INTO characters VALUES (1071,'Servant','Servant','');
INSERT INTO characters VALUES (1072,'Servant','Servant','');
INSERT INTO characters VALUES (1073,'Servants','Servants','');
INSERT INTO characters VALUES (1074,'Servants','ALL SERVANTS','');
INSERT INTO characters VALUES (1075,'Servant','Servant','');
INSERT INTO characters VALUES (1076,'Servant','SERVANT','');
INSERT INTO characters VALUES (1077,'Servant','Servant','');
INSERT INTO characters VALUES (1078,'Servilius','SERVILIUS','servant to Timon');
INSERT INTO characters VALUES (1079,'Serving-Men','Serving-Men','');
INSERT INTO characters VALUES (1080,'Seventh Citizen','Seventh Citizen','');
INSERT INTO characters VALUES (1081,'Several Citizens','Several Citizens','');
INSERT INTO characters VALUES (1082,'Sexton','Sexton','');
INSERT INTO characters VALUES (1083,'Seyton','SEYTON','An officer attending on Macduff');
INSERT INTO characters VALUES (1084,'Simon Shadow','SHADOW','country soldier');
INSERT INTO characters VALUES (1085,'Robert Shallow','SHALLOW','country Justice');
INSERT INTO characters VALUES (1086,'Shepherd','Shepherd','father to Joan of Arc');
INSERT INTO characters VALUES (1087,'Sheriff','Sheriff','');
INSERT INTO characters VALUES (1088,'Sheriff','Sheriff','');
INSERT INTO characters VALUES (1089,'Sheriff of Wiltshire','Sheriff','');
INSERT INTO characters VALUES (1090,'Shylock','SHYLOCK','a rich Jew');
INSERT INTO characters VALUES (1091,'Sicinius Velutus','SICINIUS','tribune of the people');
INSERT INTO characters VALUES (1092,'Silence','SILENCE','country Justice');
INSERT INTO characters VALUES (1093,'Silius','SILIUS','an officer in Ventidius''s army');
INSERT INTO characters VALUES (1094,'Silvia','SILVIA','beloved of Valentine');
INSERT INTO characters VALUES (1095,'Silvius','SILVIUS','daughter to the banished Duke');
INSERT INTO characters VALUES (1096,'Simonides','SIMONIDES','king of Pentapolis');
INSERT INTO characters VALUES (1097,'Simpcox','SIMPCOX','an imposter');
INSERT INTO characters VALUES (1098,'Simple','SIMPLE','servant to Slender');
INSERT INTO characters VALUES (1099,'Sir Hugh Evans','SIR HUGH EVANS','a Welsh parson');
INSERT INTO characters VALUES (1100,'Sir Hugh Mortimer','HUGH MORTIMER','uncle to the Duke of York');
INSERT INTO characters VALUES (1101,'Sir Humphrey Stafford','SIR HUMPHREY','brother to William Stafford');
INSERT INTO characters VALUES (1102,'Sir James Blount','Blount','');
INSERT INTO characters VALUES (1103,'Sir James Tyrrel','TYRREL','');
INSERT INTO characters VALUES (1104,'Sir John Fastolfe','FASTOLFE','');
INSERT INTO characters VALUES (1105,'Sir John Montgomery','MONTGOMERY','');
INSERT INTO characters VALUES (1106,'Sir John Mortimer','JOHN MORTIMER','uncle to the Duke of York');
INSERT INTO characters VALUES (1107,'Sir John Somerville','SOMERVILLE','');
INSERT INTO characters VALUES (1108,'Sir John Stanley','STANLEY','');
INSERT INTO characters VALUES (1109,'Sir Michael','SIR MICHAEL','a friend to the Archbishop of York');
INSERT INTO characters VALUES (1110,'Sir Nathaniel','SIR NATHANIEL','a curate');
INSERT INTO characters VALUES (1111,'Sir Richard Ratcliff','RATCLIFF','');
INSERT INTO characters VALUES (1112,'Sir Robert Brakenbury','BRAKENBURY','');
INSERT INTO characters VALUES (1113,'Sir Stephen Scroop','SIR STEPHEN SCROOP','');
INSERT INTO characters VALUES (1114,'Sir Thomas Gargrave','GARGRAVE','');
INSERT INTO characters VALUES (1115,'Sir Thomas Vaughan','VAUGHAN','');
INSERT INTO characters VALUES (1116,'Sir Walter Herbert','HERBERT','');
INSERT INTO characters VALUES (1117,'Sir William Catesby','CATESBY','');
INSERT INTO characters VALUES (1118,'Sir  William Glansdale','GLANSDALE','');
INSERT INTO characters VALUES (1119,'Sir William Lucy','LUCY','');
INSERT INTO characters VALUES (1120,'Sir William Stanley','STANLEY','called also Earl of Derby');
INSERT INTO characters VALUES (1121,'Siward','SIWARD','Earl of Northumberland, general of English forces');
INSERT INTO characters VALUES (1122,'Sixth Citizen','Sixth Citizen','');
INSERT INTO characters VALUES (1123,'Slender','SLENDER','cousin to Shallow');
INSERT INTO characters VALUES (1124,'Christopher Sly','SLY','a tinker');
INSERT INTO characters VALUES (1125,'Smith the Weaver','SMITH','a follower of Cade');
INSERT INTO characters VALUES (1126,'Snare','SNARE','a Sheriff''s officer');
INSERT INTO characters VALUES (1127,'Snout','SNOUT','a tinker');
INSERT INTO characters VALUES (1128,'Snug','SNUG','a joiner');
INSERT INTO characters VALUES (1129,'Soldier','Soldier','');
INSERT INTO characters VALUES (1130,'Soldier','Soldier','');
INSERT INTO characters VALUES (1131,'Soldier','Soldier','');
INSERT INTO characters VALUES (1132,'Soldier','Soldier','');
INSERT INTO characters VALUES (1133,'Soldiers','Soldiers','');
INSERT INTO characters VALUES (1134,'Soldier','Soldier','');
INSERT INTO characters VALUES (1135,'Solinus','DUKE SOLINUS','Duke of Ephesus');
INSERT INTO characters VALUES (1136,'Some Others','Some Others','');
INSERT INTO characters VALUES (1137,'Duke/Earl of Somerset','SOMERSET','John Beaufort');
INSERT INTO characters VALUES (1138,'Some Speak','Some Speak','');
INSERT INTO characters VALUES (1139,'Son','Son','who has killed his father');
INSERT INTO characters VALUES (1140,'Son','Son','Macduff''s son');
INSERT INTO characters VALUES (1141,'Soothsayer','Soothsayer','');
INSERT INTO characters VALUES (1142,'Soothsayer','Soothsayer','');
INSERT INTO characters VALUES (1143,'Soothsayer','Soothsayer','');
INSERT INTO characters VALUES (1144,'Speed','SPEED','a clownish servant to Valentine');
INSERT INTO characters VALUES (1145,'Spirit','Spirit','');
INSERT INTO characters VALUES (1146,'Starveling','STARVELING','a tailor');
INSERT INTO characters VALUES (1147,'Stephano','STEPHANO','servant to Portia');
INSERT INTO characters VALUES (1148,'Stephano','STEPHANO','a drunken butler');
INSERT INTO characters VALUES (1149,'Steward','Steward','servant to the Countess');
INSERT INTO characters VALUES (1150,'Strato','STRATO','servant to Brutus');
INSERT INTO characters VALUES (1151,'Earl of Surrey','','');
INSERT INTO characters VALUES (1152,'Surveyor','Surveyor','to the Duke of Buckingham');
INSERT INTO characters VALUES (1153,'Tailor','TAILOR','');
INSERT INTO characters VALUES (1154,'Lord Talbot/Earl of Shrewsbury','JOHN TALBOT','');
INSERT INTO characters VALUES (1155,'Tamora','TAMORA','');
INSERT INTO characters VALUES (1156,'Taurus','TAURUS','lieutenant-general to Caesar');
INSERT INTO characters VALUES (1157,'Doll Tearsheet','DOLL','');
INSERT INTO characters VALUES (1158,'Thaisa','THAISA','daughter to Simonides');
INSERT INTO characters VALUES (1159,'Thaliard','THALIARD','a lord of Antioch');
INSERT INTO characters VALUES (1160,'Thersites','THERSITES','a deformed and scurrilous Greek');
INSERT INTO characters VALUES (1161,'Theseus','THESEUS','Duke of Athens');
INSERT INTO characters VALUES (1162,'Thieves','Thieves','');
INSERT INTO characters VALUES (1163,'Third Bandit','Third Bandit','');
INSERT INTO characters VALUES (1164,'Third Citizen','Third Citizen','');
INSERT INTO characters VALUES (1165,'Third Citizen','Third Citizen','');
INSERT INTO characters VALUES (1166,'Third Citizen','Third Citizen','');
INSERT INTO characters VALUES (1167,'Third Fisherman','Third Fisherman','');
INSERT INTO characters VALUES (1168,'Third Gentleman','Third Gentleman','');
INSERT INTO characters VALUES (1169,'Third Gentleman','Third Gentleman','');
INSERT INTO characters VALUES (1170,'Third Guard','Third Guard','');
INSERT INTO characters VALUES (1171,'Third Knight','Third Knight','');
INSERT INTO characters VALUES (1172,'Third Lord','Third Lord','');
INSERT INTO characters VALUES (1173,'Third Lord','Third Lord','');
INSERT INTO characters VALUES (1174,'Third Lord','Third Lord','');
INSERT INTO characters VALUES (1175,'Third Lord','Third Lord','');
INSERT INTO characters VALUES (1176,'Third Messenger','Third Messenger','');
INSERT INTO characters VALUES (1177,'Third Neighbour','Third Neighbour','');
INSERT INTO characters VALUES (1178,'Third Officer','Third Officer','');
INSERT INTO characters VALUES (1179,'Third Outlaw','Third Outlaw','');
INSERT INTO characters VALUES (1180,'Third Pirate','Third Pirate','');
INSERT INTO characters VALUES (1181,'Third Roman','Third Roman','');
INSERT INTO characters VALUES (1182,'Third Senator','Third Senator','');
INSERT INTO characters VALUES (1183,'Third Servant','Third Servant','');
INSERT INTO characters VALUES (1184,'Third Serviceman','Third Serviceman','');
INSERT INTO characters VALUES (1185,'Third Servingman','Third Servingman','');
INSERT INTO characters VALUES (1186,'Third Soldier','Third Soldier','');
INSERT INTO characters VALUES (1187,'Third Soldier','Third Soldier','');
INSERT INTO characters VALUES (1188,'Third Stranger','Third Stranger','');
INSERT INTO characters VALUES (1189,'Third Watchman','Third Watchman','');
INSERT INTO characters VALUES (1190,'Thomas Mowbray','THOMAS MOWBRAY','Duke of Norfolk');
INSERT INTO characters VALUES (1191,'Prince Thomas','CLARENCE','Duke of Clarence');
INSERT INTO characters VALUES (1192,'Thomas Horner','HORNER','an armourer');
INSERT INTO characters VALUES (1193,'Thomas Rotherham','ARCHBISHOP OF YORK','archbishop of York');
INSERT INTO characters VALUES (1194,'Thurio','THURIO','a foolish rival to Valentine');
INSERT INTO characters VALUES (1195,'Thyreus','THYREUS','friend to Caesar');
INSERT INTO characters VALUES (1196,'Timandra','TIMANDRA','mistress to Alcibiades');
INSERT INTO characters VALUES (1197,'Time','Time','as the chorus');
INSERT INTO characters VALUES (1198,'Timon','TIMON','');
INSERT INTO characters VALUES (1199,'Tintinius','Tintinius','friend to Brutus');
INSERT INTO characters VALUES (1200,'Titania','TITANIA','queen of the fairies');
INSERT INTO characters VALUES (1201,'Titus Andronicus','TITUS ANDRONICUS','a noble Roman, general against the Goths.');
INSERT INTO characters VALUES (1202,'Titus','TITUS','servant to Timon''s creditors');
INSERT INTO characters VALUES (1203,'Touchstone','TOUCHSTONE','the court jester');
INSERT INTO characters VALUES (1204,'Townsman','Townsman','');
INSERT INTO characters VALUES (1205,'Tranio','TRANIO','');
INSERT INTO characters VALUES (1206,'Travellers','Travellers','');
INSERT INTO characters VALUES (1207,'Travers','TRAVERS','retainer of Northumberland');
INSERT INTO characters VALUES (1208,'Trebonius','TREBONIUS','a conspirator against Caesar');
INSERT INTO characters VALUES (1209,'Tressel','TRESSEL','a gentleman attending on Lady Anne');
INSERT INTO characters VALUES (1210,'Tribunes','Tribunes','');
INSERT INTO characters VALUES (1211,'Trinculo','TRINCULO','a jester');
INSERT INTO characters VALUES (1212,'Troilus','TROILUS','son of Priam, king of Troy');
INSERT INTO characters VALUES (1213,'Tubal','TUBAL','a Jew, his friend');
INSERT INTO characters VALUES (1214,'Tullus Aufidius','AUFIDIUS','general of the Vulscians');
INSERT INTO characters VALUES (1215,'Tutor of Rutland','Tutor','');
INSERT INTO characters VALUES (1216,'Tybalt','TYBALT','Nephew to Lady Capulet');
INSERT INTO characters VALUES (1217,'Tyrian Sailor','Tyrian Sailor','');
INSERT INTO characters VALUES (1218,'Ulysses','ULYSSES','a Greek prince');
INSERT INTO characters VALUES (1219,'Ursula','URSULA','Gentlewoman attending on Hero');
INSERT INTO characters VALUES (1220,'Valentine','VALENTINE','kinsman to Titus');
INSERT INTO characters VALUES (1221,'Valentine','VALENTINE','gentleman attending on the Duke');
INSERT INTO characters VALUES (1222,'Valentine','VALENTINE','a gentleman');
INSERT INTO characters VALUES (1223,'Valeria','VALERIA','friend to Virgilia');
INSERT INTO characters VALUES (1224,'Varrius','VARRIUS','friend to Pompey');
INSERT INTO characters VALUES (1225,'Varrius','VARRIUS','');
INSERT INTO characters VALUES (1226,'Varro','VARRO','servant to Brutus');
INSERT INTO characters VALUES (1227,'Varro''s First Servant','Varro''s First Servant','');
INSERT INTO characters VALUES (1228,'Varro''s Second Servant','Varro''s Second Servant','');
INSERT INTO characters VALUES (1229,'Sir Nicholas Vaux','VAUX','');
INSERT INTO characters VALUES (1230,'Vaux','VAUX','');
INSERT INTO characters VALUES (1231,'Ventidius','VENTIDIUS','one of Timon''s false friends');
INSERT INTO characters VALUES (1232,'Ventidius','VENTIDIUS','friend to Antony');
INSERT INTO characters VALUES (1233,'Verges','VERGES','A headborough');
INSERT INTO characters VALUES (1234,'Vernon','VERNON','of the White Rose, or York, faction');
INSERT INTO characters VALUES (1235,'Vincentio','VINCENTIO','a merchant of Pisa');
INSERT INTO characters VALUES (1236,'Vincentio','DUKE VINCENTIO','the Duke');
INSERT INTO characters VALUES (1237,'Vintner','Vintner','');
INSERT INTO characters VALUES (1238,'Viola','VIOLA','');
INSERT INTO characters VALUES (1239,'Violenta','VIOLENTA','neighbor and friend to the widow');
INSERT INTO characters VALUES (1240,'Virgilia','VIRGILIA','wife to Coriolanus');
INSERT INTO characters VALUES (1241,'Volsce','Volsce','');
INSERT INTO characters VALUES (1242,'Voltemand','Volt','courtier');
INSERT INTO characters VALUES (1243,'Volumnia','VOLUMNIA','mother to Coriolanus');
INSERT INTO characters VALUES (1244,'Volumnius','VOLUMNIUS','friend to Brutus');
INSERT INTO characters VALUES (1245,'Walter Whitmore','WHITMORE','');
INSERT INTO characters VALUES (1246,'Thomas Wart','WART','country soldier');
INSERT INTO characters VALUES (1247,'Earl of Warwick','WARWICK','');
INSERT INTO characters VALUES (1248,'Watch','Watch','');
INSERT INTO characters VALUES (1249,'Watchman','Watchman','');
INSERT INTO characters VALUES (1250,'Earl of Westmoreland','WESTMORELAND','');
INSERT INTO characters VALUES (1251,'Widow','WIDOW','');
INSERT INTO characters VALUES (1252,'Widow','Widow','an old widow of Florence');
INSERT INTO characters VALUES (1253,'Simpcox''s Wife','Wife','');
INSERT INTO characters VALUES (1254,'William','WILLIAM','a country fellow, in love with Audrey');
INSERT INTO characters VALUES (1255,'Williams','WILLIAMS','soldier in King Henry''s army');
INSERT INTO characters VALUES (1256,'William Page','WILLIAM PAGE','a boy, son to Page');
INSERT INTO characters VALUES (1257,'William Stafford','WILLIAM STAFFORD','brother to Sir Humphrey Stafford');
INSERT INTO characters VALUES (1258,'Cardinal Wolsey','CARDINAL WOLSEY','');
INSERT INTO characters VALUES (1259,'Woodvile','WOODVILE','lieutenant of the Tower');
INSERT INTO characters VALUES (1260,'Earl of Worcester','EARL OF WORCESTER','');
INSERT INTO characters VALUES (1261,'(stage directions)', 'xxx', '');
INSERT INTO characters VALUES (1262,'Duke of York','YORK','cousin to the king');
INSERT INTO characters VALUES (1263,'Young Clifford','YOUNG CLIFFORD','');
INSERT INTO characters VALUES (1264,'Young Coriolanus','Young CORIOLANUS','son to Coriolanus');
INSERT INTO characters VALUES (1265,'Young Lucius','Young LUCIUS','son to Lucius');
INSERT INTO characters VALUES (1266,'Young Siward','YOUNG SIWARD','Siward''s son');
COMMIT;
